import AsyncStorage from "@react-native-async-storage/async-storage";
import React, { createContext, useCallback, useContext, useEffect, useState } from "react";

export type Lang = "en" | "ht" | "fr" | "es" | "pt" | "de" | "hi" | "fil" | "ha" | "zu" | "af";

const LANG_KEY = "flexa_lang";

export const LANGUAGES: { code: Lang; label: string; native: string; flag: string }[] = [
  { code: "ht",  label: "Kreyòl Ayisyen",   native: "Kreyòl Ayisyen",   flag: "🇭🇹" },
  { code: "fr",  label: "Français",         native: "Français",         flag: "🇫🇷" },
  { code: "es",  label: "Español",          native: "Español",          flag: "🇪🇸" },
  { code: "en",  label: "English",          native: "English",          flag: "🇺🇸" },
  { code: "pt",  label: "Português",        native: "Português",        flag: "🇧🇷" },
  { code: "de",  label: "Deutsch",          native: "Deutsch",          flag: "🇩🇪" },
  { code: "hi",  label: "Hindi",            native: "हिन्दी",            flag: "🇮🇳" },
  { code: "fil", label: "Filipino",         native: "Filipino",         flag: "🇵🇭" },
  { code: "ha",  label: "Hausa",            native: "Hausa",            flag: "🇳🇬" },
  { code: "zu",  label: "isiZulu",          native: "isiZulu",          flag: "🇿🇦" },
  { code: "af",  label: "Afrikaans",        native: "Afrikaans",        flag: "🇿🇦" },
];

const T: Record<Lang, Record<string, string>> = {
  en: {
    tabHome: "Home", tabSearch: "Search", tabSell: "Sell", tabMessages: "Messages", tabProfile: "Profile",
    back: "Back", loading: "Loading...", cancel: "Cancel", save: "Save", ok: "OK", greeting: "Hello",
    allCategories: "All", noListings: "No listings",
    sponsored: "Sponsored", description: "Description", seller: "Seller", profile: "Profile",
    listingContact: "Contact Seller", listingOffer: "Make an Offer", listingOfferSent: "Offer sent!",
    listingChatErr: "Chat error", listingNotFound: "Listing not found", listingLoadErr: "Load error",
    listingCondition: "Condition",
    myFavorites: "My Favorites", myOrders: "My Orders", myWallet: "FM Wallet", myKyc: "Identity (KYC)",
    myReviews: "Reviews", mySettings: "Settings", myListings: "My Listings",
    seeAll: "See all", logout: "Sign out", logoutTitle: "Sign out",
    logoutMsg: "Are you sure you want to sign out?",
    listingsCount: "Listings", verified: "Verified", notVerified: "Unverified",
    rating: "Rating", agentProfile: "Agent Profile",
    sAccount: "Account", sEditProfile: "Edit Profile",
    sEditProfileHint: "Open the FlexaMarket website to edit your profile.",
    sPasswordSecurity: "Password & Security",
    sPasswordSecurityHint: "Go to Settings → Security on FlexaMarket to change your password.",
    sKyc: "Identity Verification (KYC)", sPhone: "Phone & OTP",
    sPhoneHint: "Contact FlexaMarket support to change your phone number.",
    sPreferences: "Preferences", sNotifications: "Notifications",
    sNotifOn: "Enabled", sNotifOff: "Disabled", sLanguage: "Language",
    sAppearance: "Appearance", sDarkMode: "Dark mode",
    sFinances: "Finances", sWalletFM: "FM Wallet",
    sPayoutAccount: "Seller Payout Account",
    sPayoutAccountHint: "Configure your MonCash & bank account in FlexaMarket Settings.",
    sSupport: "Support", sHelpSupport: "Help & Support",
    sHelpSupportHint: "Email support@flexamarket.com or use the Support section on the website.",
    sTerms: "Terms of Service",
    sTermsHint: "Visit flexamarket.com/terms to read the terms of service.",
    sAbout: "About FlexaMarket",
    sAboutMsg: "First buy & sell marketplace in the Caribbean.\n\nVersion 1.0.0\n© 2026 FlexaMarket",
    sLogout: "Sign out",
    ordersTitle: "Orders", ordersBuying: "Buying", ordersSelling: "Selling",
    noOrders: "No orders", noOrdersHint: "Your orders will appear here when you buy or sell.",
    walletTitle: "FM Wallet", realBalance: "Real Balance", promoBalance: "Promo",
    unlockedBalance: "Unlocked", recharge: "Top Up", send: "Send", withdraw: "Withdraw",
    noTransactions: "No transactions", noTransactionsHint: "Your transactions will appear here.",
    txHistory: "Transaction History",
    rechargeTitle: "Top Up Wallet",
    rechargeMsg: "Send MonCash to +509 40-40-1234 then enter the transaction number in support for quick confirmation.",
    sendTitle: "Send Money",
    sendMsg: "Use the 'Send Money' section on FlexaMarket to make a P2P transfer.",
    withdrawTitle: "Withdraw",
    withdrawMsg: "Contact support to request a withdrawal.",
    kycTitle: "Identity Verification", kycApproved: "Identity Verified ✅",
    kycApprovedSub: "Your account is verified. You can complete all transactions without limits.",
    kycPending: "Pending Review",
    kycPendingSub: "Your application has been submitted. Admin will review it within 24 hours.",
    kycRejected: "Application Rejected",
    kycInfoText: "Identity verification is required for transfers over $500 and large transactions.",
    kycSubmitting: "Submitting...", kycErrTitle: "Error",
    kycErrDocs: "Please upload an ID photo and selfie.",
    kycSubmitTitle: "Submitted!", kycSubmitMsg: "Your KYC has been submitted. Admin will review within 24 hours.",
    kycErrMsg: "Submission failed. Please try again.",
    kycDocType: "Document Type", kycNatId: "National ID", kycPassport: "Passport",
    kycDrivingLicense: "Driver's License", kycDocFront: "ID Photo",
    kycDocFrontHint: "Tap to upload the front of your ID", kycSelfie: "Selfie",
    kycSelfieHint: "Tap to upload a selfie", kycSubmitBtn: "Submit Verification",
    inboxTitle: "Messages", noConversations: "No conversations",
    noConvHint: "Tap a listing and contact the seller to get started.",
    sellTitle: "Create Listing", searchTitle: "Search",
    searchNoResults: "No results", searchHint: "Try another keyword.",
    chatOnline: "Online", notVerifiedKyc: "Unverified",
    languagesTitle: "Languages", selectLanguage: "Select your language",
    loginTitle: "Sign In", loginSubtitle: "Welcome back! Enter your account.",
    loginEmailPlaceholder: "you@email.com", loginPassword: "Password",
    loginBtn: "Sign In", loginOr: "or", loginCreateBtn: "Create an account",
    registerTitle: "Create Account", registerSubtitle: "Join the FlexaMarket community.",
    registerFullName: "Full Name", registerFullNamePlaceholder: "John Smith",
    registerPasswordPlaceholder: "At least 6 characters",
    registerCountry: "Country", registerBtn: "Create Account",
    errFillAll: "Please fill in all required fields.",
    errPassword6: "Password must be at least 6 characters.",
    errLoginFailed: "Login failed", errRegisterFailed: "Registration failed",
    errConnection: "Connection error", alreadyAccount: "Already have an account?",
  },

  ht: {
    tabHome: "Akèy", tabSearch: "Chèche", tabSell: "Vann", tabMessages: "Mesaj", tabProfile: "Pwofil",
    back: "Retounen", loading: "Ap chaje...", cancel: "Anile", save: "Sove", ok: "OK", greeting: "Bonjou",
    allCategories: "Tout", noListings: "Pa gen annons",
    sponsored: "Sponsorisé", description: "Deskripsyon", seller: "Vandè", profile: "Pwofil",
    listingContact: "Kontakte Vandè", listingOffer: "Fè yon Òf", listingOfferSent: "Òf voye!",
    listingChatErr: "Erè chat", listingNotFound: "Annons pa jwenn", listingLoadErr: "Erè chajman",
    listingCondition: "Kondisyon",
    myFavorites: "Favori Mwen", myOrders: "Kòmand yo", myWallet: "Pòtfèy FM", myKyc: "Verifikasyon (KYC)",
    myReviews: "Evalyasyon", mySettings: "Paramèt", myListings: "Annons Mwen",
    seeAll: "Wè tout", logout: "Dekonekte", logoutTitle: "Dekonekte",
    logoutMsg: "Ou sèten ou vle dekonekte?",
    listingsCount: "Annons", verified: "Verifye", notVerified: "Pa verifye",
    rating: "Nòt", agentProfile: "Pwofil Ajan Mwen",
    sAccount: "Kont", sEditProfile: "Modifye Pwofil",
    sEditProfileHint: "Ouvè sit entènèt FlexaMarket pou modifye pwofil ou a.",
    sPasswordSecurity: "Modpas & Sekirite",
    sPasswordSecurityHint: "Ale nan Paramèt → Sekirite sou sit entènèt FlexaMarket pou chanje modpas ou.",
    sKyc: "Verifikasyon Idantite (KYC)", sPhone: "Telefòn & OTP",
    sPhoneHint: "Kontakte sipò FlexaMarket pou chanje nimewo telefòn ou.",
    sPreferences: "Preferans", sNotifications: "Notifikasyon",
    sNotifOn: "Aktif", sNotifOff: "Dezaktive", sLanguage: "Lang",
    sAppearance: "Aparans", sDarkMode: "Mode nwa",
    sFinances: "Finans", sWalletFM: "Pòtfèy FM",
    sPayoutAccount: "Kont Peman Vandè",
    sPayoutAccountHint: "Konfigire kont MonCash ak Bank ou nan Paramèt sou sit entènèt FlexaMarket.",
    sSupport: "Asistans", sHelpSupport: "Sipò",
    sHelpSupportHint: "Voye yon mesaj nan support@flexamarket.com oswa itilize seksyon Sipò sou sit entènèt la.",
    sTerms: "Kondisyon Itilizasyon",
    sTermsHint: "Ale sou flexamarket.com/terms pou li kondisyon itilizasyon yo.",
    sAbout: "Sou FlexaMarket",
    sAboutMsg: "Premye marketplace achte & vann ann Ayiti.\n\nVèsyon 1.0.0\n© 2026 FlexaMarket",
    sLogout: "Dekonekte",
    ordersTitle: "Kòmand yo", ordersBuying: "Achte", ordersSelling: "Vann",
    noOrders: "Pa gen kòmand", noOrdersHint: "Kòmand ou yo parèt isit lè ou achte oswa vann yon bagay.",
    walletTitle: "Pòtfèy FM", realBalance: "Balans Reyèl", promoBalance: "Promo",
    unlockedBalance: "Debloke", recharge: "Recharge", send: "Voye", withdraw: "Retire",
    noTransactions: "Pa gen tranzaksyon", noTransactionsHint: "Tranzaksyon ou yo parèt isit.",
    txHistory: "Istwa Tranzaksyon",
    rechargeTitle: "Recharge Pòtfèy",
    rechargeMsg: "Voye MonCash nan +509 40-40-1234 epi mete nimewo tranzaksyon ou a nan sipò pou konfirmasyon rapid.",
    sendTitle: "Voye Lajan",
    sendMsg: "Itilize seksyon 'Voye Lajan' sou sit entènèt FlexaMarket pou fè transfè P2P.",
    withdrawTitle: "Retire Lajan",
    withdrawMsg: "Kontakte sipò pou demande yon retrè.",
    kycTitle: "Verifikasyon Idantite", kycApproved: "Idantite Verifye ✅",
    kycApprovedSub: "Kont ou verifye. Ou ka fè tout tranzaksyon san limit.",
    kycPending: "Annatant Revizyon",
    kycPendingSub: "Demann ou soumèt. Admin pral revize li nan 24 èdtan.",
    kycRejected: "Demann Refize",
    kycInfoText: "Verifikasyon idantite obligatwa pou transfè plis pase $500 ak pou gwo tranzaksyon.",
    kycSubmitting: "Ap soumèt...", kycErrTitle: "Erè",
    kycErrDocs: "Ou bezwen telechaje foto dokiman ak selfie ou.",
    kycSubmitTitle: "Soumèt!", kycSubmitMsg: "Demann KYC ou soumèt. Admin pral revize li nan 24 èdtan.",
    kycErrMsg: "Echèk soumisyon. Eseye ankò.",
    kycDocType: "Tip Dokiman", kycNatId: "Kat Nasyonal", kycPassport: "Paspò",
    kycDrivingLicense: "Lisans Kondi", kycDocFront: "Foto Dokiman ID",
    kycDocFrontHint: "Klike pou telechaje foto devan ID ou a", kycSelfie: "Selfie",
    kycSelfieHint: "Klike pou telechaje yon selfie", kycSubmitBtn: "Soumèt Verifikasyon",
    inboxTitle: "Bwat Mesaj", noConversations: "Pa gen konvèsasyon",
    noConvHint: "Klik sou yon annons epi kontakte vandè a pou kòmanse.",
    sellTitle: "Kreye Annons", searchTitle: "Chèche",
    searchNoResults: "Pa gen rezilta", searchHint: "Eseye yon lòt mo rechèch.",
    chatOnline: "An liy", notVerifiedKyc: "Pa verifye",
    languagesTitle: "Chwa Lang", selectLanguage: "Chwazi lang ou",
    loginTitle: "Konekte", loginSubtitle: "Bon retonn! Antre nan kont ou.",
    loginEmailPlaceholder: "ou@email.com", loginPassword: "Modepas",
    loginBtn: "Konekte", loginOr: "oswa", loginCreateBtn: "Kreye yon kont",
    registerTitle: "Kreye Kont", registerSubtitle: "Rejwenn kominote FlexaMarket la.",
    registerFullName: "Non Konplè", registerFullNamePlaceholder: "Jan Pyè",
    registerPasswordPlaceholder: "Omwen 6 karaktè",
    registerCountry: "Peyi", registerBtn: "Kreye Kont",
    errFillAll: "Tanpri ranpli tout chan obligatwa yo.",
    errPassword6: "Modepas dwe gen omwen 6 karaktè.",
    errLoginFailed: "Koneksyon echwe", errRegisterFailed: "Enskripsyon echwe",
    errConnection: "Erè koneksyon", alreadyAccount: "Ou gen yon kont deja?",
  },

  fr: {
    tabHome: "Accueil", tabSearch: "Rechercher", tabSell: "Vendre", tabMessages: "Messages", tabProfile: "Profil",
    back: "Retour", loading: "Chargement...", cancel: "Annuler", save: "Enregistrer", ok: "OK", greeting: "Bonjour",
    allCategories: "Tout", noListings: "Aucune annonce",
    sponsored: "Sponsorisé", description: "Description", seller: "Vendeur", profile: "Profil",
    listingContact: "Contacter le vendeur", listingOffer: "Faire une offre", listingOfferSent: "Offre envoyée !",
    listingChatErr: "Erreur de chat", listingNotFound: "Annonce introuvable", listingLoadErr: "Erreur de chargement",
    listingCondition: "État",
    myFavorites: "Mes Favoris", myOrders: "Mes Commandes", myWallet: "Portefeuille FM", myKyc: "Vérification (KYC)",
    myReviews: "Avis reçus", mySettings: "Paramètres", myListings: "Mes Annonces",
    seeAll: "Voir tout", logout: "Déconnexion", logoutTitle: "Déconnexion",
    logoutMsg: "Êtes-vous sûr de vouloir vous déconnecter ?",
    listingsCount: "Annonces", verified: "Vérifié", notVerified: "Non vérifié",
    rating: "Note", agentProfile: "Mon Profil Agent",
    sAccount: "Compte", sEditProfile: "Modifier le profil",
    sEditProfileHint: "Accédez au site FlexaMarket pour modifier votre profil.",
    sPasswordSecurity: "Mot de passe & Sécurité",
    sPasswordSecurityHint: "Allez dans Paramètres → Sécurité sur FlexaMarket pour changer votre mot de passe.",
    sKyc: "Vérification d'identité (KYC)", sPhone: "Téléphone & OTP",
    sPhoneHint: "Contactez le support FlexaMarket pour changer votre numéro de téléphone.",
    sPreferences: "Préférences", sNotifications: "Notifications",
    sNotifOn: "Activé", sNotifOff: "Désactivé", sLanguage: "Langue",
    sAppearance: "Apparence", sDarkMode: "Mode sombre",
    sFinances: "Finances", sWalletFM: "Portefeuille FM",
    sPayoutAccount: "Compte de paiement vendeur",
    sPayoutAccountHint: "Configurez votre compte MonCash et bancaire dans les Paramètres sur FlexaMarket.",
    sSupport: "Assistance", sHelpSupport: "Support",
    sHelpSupportHint: "Envoyez un message à support@flexamarket.com ou utilisez la section Support.",
    sTerms: "Conditions d'utilisation",
    sTermsHint: "Visitez flexamarket.com/terms pour lire les conditions d'utilisation.",
    sAbout: "À propos de FlexaMarket",
    sAboutMsg: "Premier marketplace d'achat & vente en Haïti.\n\nVersion 1.0.0\n© 2026 FlexaMarket",
    sLogout: "Déconnexion",
    ordersTitle: "Commandes", ordersBuying: "Achats", ordersSelling: "Ventes",
    noOrders: "Aucune commande", noOrdersHint: "Vos commandes apparaissent ici lorsque vous achetez ou vendez.",
    walletTitle: "Portefeuille FM", realBalance: "Solde Réel", promoBalance: "Promo",
    unlockedBalance: "Débloqué", recharge: "Recharger", send: "Envoyer", withdraw: "Retirer",
    noTransactions: "Aucune transaction", noTransactionsHint: "Vos transactions apparaissent ici.",
    txHistory: "Historique des transactions",
    rechargeTitle: "Recharger le portefeuille",
    rechargeMsg: "Envoyez MonCash au +509 40-40-1234 puis entrez le numéro de transaction dans le support.",
    sendTitle: "Envoyer de l'argent",
    sendMsg: "Utilisez la section 'Envoyer' sur FlexaMarket pour faire un transfert P2P.",
    withdrawTitle: "Retirer",
    withdrawMsg: "Contactez le support pour demander un retrait.",
    kycTitle: "Vérification d'identité", kycApproved: "Identité vérifiée ✅",
    kycApprovedSub: "Votre compte est vérifié. Vous pouvez effectuer toutes les transactions sans limite.",
    kycPending: "En attente de révision",
    kycPendingSub: "Votre demande a été soumise. L'administrateur la révisera dans les 24 heures.",
    kycRejected: "Demande refusée",
    kycInfoText: "La vérification d'identité est obligatoire pour les transferts de plus de 500 $.",
    kycSubmitting: "Envoi en cours...", kycErrTitle: "Erreur",
    kycErrDocs: "Vous devez télécharger une photo de document et un selfie.",
    kycSubmitTitle: "Soumis !", kycSubmitMsg: "Votre demande KYC a été soumise. L'admin révisera dans 24 h.",
    kycErrMsg: "Échec de soumission. Réessayez.",
    kycDocType: "Type de document", kycNatId: "Carte nationale", kycPassport: "Passeport",
    kycDrivingLicense: "Permis de conduire", kycDocFront: "Photo de la pièce d'identité",
    kycDocFrontHint: "Cliquez pour télécharger le recto de votre pièce d'identité", kycSelfie: "Selfie",
    kycSelfieHint: "Cliquez pour télécharger un selfie", kycSubmitBtn: "Soumettre la vérification",
    inboxTitle: "Messages", noConversations: "Aucune conversation",
    noConvHint: "Cliquez sur une annonce et contactez le vendeur pour commencer.",
    sellTitle: "Créer une annonce", searchTitle: "Rechercher",
    searchNoResults: "Aucun résultat", searchHint: "Essayez un autre mot-clé.",
    chatOnline: "En ligne", notVerifiedKyc: "Non vérifié",
    languagesTitle: "Langues", selectLanguage: "Choisissez votre langue",
    loginTitle: "Se connecter", loginSubtitle: "Bon retour ! Connectez-vous à votre compte.",
    loginEmailPlaceholder: "vous@email.com", loginPassword: "Mot de passe",
    loginBtn: "Se connecter", loginOr: "ou", loginCreateBtn: "Créer un compte",
    registerTitle: "Créer un compte", registerSubtitle: "Rejoignez la communauté FlexaMarket.",
    registerFullName: "Nom complet", registerFullNamePlaceholder: "Jean Dupont",
    registerPasswordPlaceholder: "Au moins 6 caractères",
    registerCountry: "Pays", registerBtn: "Créer un compte",
    errFillAll: "Veuillez remplir tous les champs obligatoires.",
    errPassword6: "Le mot de passe doit comporter au moins 6 caractères.",
    errLoginFailed: "Connexion échouée", errRegisterFailed: "Inscription échouée",
    errConnection: "Erreur de connexion", alreadyAccount: "Vous avez déjà un compte ?",
  },

  es: {
    tabHome: "Inicio", tabSearch: "Buscar", tabSell: "Vender", tabMessages: "Mensajes", tabProfile: "Perfil",
    back: "Atrás", loading: "Cargando...", cancel: "Cancelar", save: "Guardar", ok: "OK", greeting: "Hola",
    allCategories: "Todo", noListings: "Sin anuncios",
    sponsored: "Patrocinado", description: "Descripción", seller: "Vendedor", profile: "Perfil",
    listingContact: "Contactar al vendedor", listingOffer: "Hacer una oferta", listingOfferSent: "¡Oferta enviada!",
    listingChatErr: "Error de chat", listingNotFound: "Anuncio no encontrado", listingLoadErr: "Error al cargar",
    listingCondition: "Condición",
    myFavorites: "Mis Favoritos", myOrders: "Mis Pedidos", myWallet: "Billetera FM", myKyc: "Verificación (KYC)",
    myReviews: "Mis Reseñas", mySettings: "Configuración", myListings: "Mis Anuncios",
    seeAll: "Ver todo", logout: "Cerrar sesión", logoutTitle: "Cerrar sesión",
    logoutMsg: "¿Estás seguro de que quieres cerrar sesión?",
    listingsCount: "Anuncios", verified: "Verificado", notVerified: "No verificado",
    rating: "Calificación", agentProfile: "Perfil de Agente",
    sAccount: "Cuenta", sEditProfile: "Editar perfil",
    sEditProfileHint: "Abre el sitio FlexaMarket para editar tu perfil.",
    sPasswordSecurity: "Contraseña & Seguridad",
    sPasswordSecurityHint: "Ve a Configuración → Seguridad en FlexaMarket para cambiar tu contraseña.",
    sKyc: "Verificación de Identidad (KYC)", sPhone: "Teléfono & OTP",
    sPhoneHint: "Contacta al soporte de FlexaMarket para cambiar tu número de teléfono.",
    sPreferences: "Preferencias", sNotifications: "Notificaciones",
    sNotifOn: "Activado", sNotifOff: "Desactivado", sLanguage: "Idioma",
    sAppearance: "Apariencia", sDarkMode: "Modo oscuro",
    sFinances: "Finanzas", sWalletFM: "Billetera FM",
    sPayoutAccount: "Cuenta de pago del vendedor",
    sPayoutAccountHint: "Configura tu cuenta MonCash y bancaria en FlexaMarket.",
    sSupport: "Soporte", sHelpSupport: "Ayuda & Soporte",
    sHelpSupportHint: "Envía un correo a support@flexamarket.com o usa la sección de Soporte.",
    sTerms: "Términos de Servicio",
    sTermsHint: "Visita flexamarket.com/terms para leer los términos.",
    sAbout: "Acerca de FlexaMarket",
    sAboutMsg: "El primer marketplace de compra y venta en el Caribe.\n\nVersión 1.0.0\n© 2026 FlexaMarket",
    sLogout: "Cerrar sesión",
    ordersTitle: "Pedidos", ordersBuying: "Comprando", ordersSelling: "Vendiendo",
    noOrders: "Sin pedidos", noOrdersHint: "Tus pedidos aparecerán aquí cuando compres o vendas.",
    walletTitle: "Billetera FM", realBalance: "Saldo Real", promoBalance: "Promo",
    unlockedBalance: "Desbloqueado", recharge: "Recargar", send: "Enviar", withdraw: "Retirar",
    noTransactions: "Sin transacciones", noTransactionsHint: "Tus transacciones aparecerán aquí.",
    txHistory: "Historial de transacciones",
    rechargeTitle: "Recargar billetera",
    rechargeMsg: "Envía MonCash al +509 40-40-1234 y escribe el número de transacción en soporte.",
    sendTitle: "Enviar dinero",
    sendMsg: "Usa la sección 'Enviar' en FlexaMarket para hacer una transferencia P2P.",
    withdrawTitle: "Retirar fondos",
    withdrawMsg: "Contacta al soporte para solicitar un retiro.",
    kycTitle: "Verificación de Identidad", kycApproved: "Identidad Verificada ✅",
    kycApprovedSub: "Tu cuenta está verificada. Puedes realizar todas las transacciones sin límites.",
    kycPending: "En revisión",
    kycPendingSub: "Tu solicitud fue enviada. El admin la revisará en 24 horas.",
    kycRejected: "Solicitud rechazada",
    kycInfoText: "La verificación de identidad es requerida para transferencias mayores a $500.",
    kycSubmitting: "Enviando...", kycErrTitle: "Error",
    kycErrDocs: "Debes subir una foto de tu documento y un selfie.",
    kycSubmitTitle: "¡Enviado!", kycSubmitMsg: "Tu KYC fue enviado. El admin lo revisará en 24 horas.",
    kycErrMsg: "Error al enviar. Inténtalo de nuevo.",
    kycDocType: "Tipo de documento", kycNatId: "Cédula Nacional", kycPassport: "Pasaporte",
    kycDrivingLicense: "Licencia de conducir", kycDocFront: "Foto del documento",
    kycDocFrontHint: "Toca para subir el frente de tu documento", kycSelfie: "Selfie",
    kycSelfieHint: "Toca para subir un selfie", kycSubmitBtn: "Enviar verificación",
    inboxTitle: "Mensajes", noConversations: "Sin conversaciones",
    noConvHint: "Toca un anuncio y contacta al vendedor para comenzar.",
    sellTitle: "Crear anuncio", searchTitle: "Buscar",
    searchNoResults: "Sin resultados", searchHint: "Intenta con otra palabra clave.",
    chatOnline: "En línea", notVerifiedKyc: "No verificado",
    languagesTitle: "Idiomas", selectLanguage: "Elige tu idioma",
    loginTitle: "Iniciar sesión", loginSubtitle: "¡Bienvenido de vuelta! Ingresa a tu cuenta.",
    loginEmailPlaceholder: "tu@email.com", loginPassword: "Contraseña",
    loginBtn: "Iniciar sesión", loginOr: "o", loginCreateBtn: "Crear una cuenta",
    registerTitle: "Crear cuenta", registerSubtitle: "Únete a la comunidad FlexaMarket.",
    registerFullName: "Nombre completo", registerFullNamePlaceholder: "Juan García",
    registerPasswordPlaceholder: "Al menos 6 caracteres",
    registerCountry: "País", registerBtn: "Crear cuenta",
    errFillAll: "Por favor completa todos los campos obligatorios.",
    errPassword6: "La contraseña debe tener al menos 6 caracteres.",
    errLoginFailed: "Error al iniciar sesión", errRegisterFailed: "Error al registrarse",
    errConnection: "Error de conexión", alreadyAccount: "¿Ya tienes una cuenta?",
  },

  pt: {
    tabHome: "Início", tabSearch: "Pesquisar", tabSell: "Vender", tabMessages: "Mensagens", tabProfile: "Perfil",
    back: "Voltar", loading: "Carregando...", cancel: "Cancelar", save: "Salvar", ok: "OK", greeting: "Olá",
    allCategories: "Tudo", noListings: "Sem anúncios",
    sponsored: "Patrocinado", description: "Descrição", seller: "Vendedor", profile: "Perfil",
    listingContact: "Contatar vendedor", listingOffer: "Fazer uma oferta", listingOfferSent: "Oferta enviada!",
    listingChatErr: "Erro no chat", listingNotFound: "Anúncio não encontrado", listingLoadErr: "Erro ao carregar",
    listingCondition: "Condição",
    myFavorites: "Meus Favoritos", myOrders: "Meus Pedidos", myWallet: "Carteira FM", myKyc: "Verificação (KYC)",
    myReviews: "Avaliações", mySettings: "Configurações", myListings: "Meus Anúncios",
    seeAll: "Ver tudo", logout: "Sair", logoutTitle: "Sair",
    logoutMsg: "Tem certeza que deseja sair?",
    listingsCount: "Anúncios", verified: "Verificado", notVerified: "Não verificado",
    rating: "Avaliação", agentProfile: "Perfil de Agente",
    sAccount: "Conta", sEditProfile: "Editar perfil",
    sEditProfileHint: "Acesse o site FlexaMarket para editar seu perfil.",
    sPasswordSecurity: "Senha & Segurança",
    sPasswordSecurityHint: "Vá para Configurações → Segurança no FlexaMarket para alterar sua senha.",
    sKyc: "Verificação de Identidade (KYC)", sPhone: "Telefone & OTP",
    sPhoneHint: "Contate o suporte FlexaMarket para alterar seu número de telefone.",
    sPreferences: "Preferências", sNotifications: "Notificações",
    sNotifOn: "Ativado", sNotifOff: "Desativado", sLanguage: "Idioma",
    sAppearance: "Aparência", sDarkMode: "Modo escuro",
    sFinances: "Finanças", sWalletFM: "Carteira FM",
    sPayoutAccount: "Conta de pagamento do vendedor",
    sPayoutAccountHint: "Configure sua conta MonCash e bancária nas Configurações do FlexaMarket.",
    sSupport: "Suporte", sHelpSupport: "Ajuda & Suporte",
    sHelpSupportHint: "Envie um e-mail para support@flexamarket.com ou use a seção de Suporte.",
    sTerms: "Termos de Serviço",
    sTermsHint: "Visite flexamarket.com/terms para ler os termos.",
    sAbout: "Sobre FlexaMarket",
    sAboutMsg: "Primeiro marketplace de compra e venda no Caribe.\n\nVersão 1.0.0\n© 2026 FlexaMarket",
    sLogout: "Sair",
    ordersTitle: "Pedidos", ordersBuying: "Comprando", ordersSelling: "Vendendo",
    noOrders: "Sem pedidos", noOrdersHint: "Seus pedidos aparecerão aqui quando comprar ou vender.",
    walletTitle: "Carteira FM", realBalance: "Saldo Real", promoBalance: "Promo",
    unlockedBalance: "Desbloqueado", recharge: "Recarregar", send: "Enviar", withdraw: "Sacar",
    noTransactions: "Sem transações", noTransactionsHint: "Suas transações aparecerão aqui.",
    txHistory: "Histórico de transações",
    rechargeTitle: "Recarregar carteira",
    rechargeMsg: "Envie MonCash para +509 40-40-1234 e informe o número da transação no suporte.",
    sendTitle: "Enviar dinheiro",
    sendMsg: "Use a seção 'Enviar' no FlexaMarket para fazer uma transferência P2P.",
    withdrawTitle: "Sacar fundos",
    withdrawMsg: "Contate o suporte para solicitar um saque.",
    kycTitle: "Verificação de Identidade", kycApproved: "Identidade Verificada ✅",
    kycApprovedSub: "Sua conta está verificada. Você pode realizar todas as transações sem limites.",
    kycPending: "Em análise",
    kycPendingSub: "Sua solicitação foi enviada. O admin revisará em 24 horas.",
    kycRejected: "Solicitação recusada",
    kycInfoText: "A verificação de identidade é obrigatória para transferências acima de $500.",
    kycSubmitting: "Enviando...", kycErrTitle: "Erro",
    kycErrDocs: "Você deve enviar uma foto do documento e um selfie.",
    kycSubmitTitle: "Enviado!", kycSubmitMsg: "Seu KYC foi enviado. O admin revisará em 24 horas.",
    kycErrMsg: "Falha no envio. Tente novamente.",
    kycDocType: "Tipo de documento", kycNatId: "Cartão Nacional", kycPassport: "Passaporte",
    kycDrivingLicense: "Carteira de motorista", kycDocFront: "Foto do documento",
    kycDocFrontHint: "Toque para enviar a frente do documento", kycSelfie: "Selfie",
    kycSelfieHint: "Toque para enviar um selfie", kycSubmitBtn: "Enviar verificação",
    inboxTitle: "Mensagens", noConversations: "Sem conversas",
    noConvHint: "Toque em um anúncio e contate o vendedor para começar.",
    sellTitle: "Criar anúncio", searchTitle: "Pesquisar",
    searchNoResults: "Sem resultados", searchHint: "Tente outra palavra-chave.",
    chatOnline: "Online", notVerifiedKyc: "Não verificado",
    languagesTitle: "Idiomas", selectLanguage: "Escolha seu idioma",
    loginTitle: "Entrar", loginSubtitle: "Bem-vindo de volta! Acesse sua conta.",
    loginEmailPlaceholder: "voce@email.com", loginPassword: "Senha",
    loginBtn: "Entrar", loginOr: "ou", loginCreateBtn: "Criar uma conta",
    registerTitle: "Criar conta", registerSubtitle: "Junte-se à comunidade FlexaMarket.",
    registerFullName: "Nome completo", registerFullNamePlaceholder: "João Silva",
    registerPasswordPlaceholder: "Pelo menos 6 caracteres",
    registerCountry: "País", registerBtn: "Criar conta",
    errFillAll: "Por favor preencha todos os campos obrigatórios.",
    errPassword6: "A senha deve ter pelo menos 6 caracteres.",
    errLoginFailed: "Falha ao entrar", errRegisterFailed: "Falha no registro",
    errConnection: "Erro de conexão", alreadyAccount: "Já tem uma conta?",
  },

  de: {
    tabHome: "Startseite", tabSearch: "Suchen", tabSell: "Verkaufen", tabMessages: "Nachrichten", tabProfile: "Profil",
    back: "Zurück", loading: "Laden...", cancel: "Abbrechen", save: "Speichern", ok: "OK", greeting: "Hallo",
    allCategories: "Alle", noListings: "Keine Anzeigen",
    sponsored: "Gesponsert", description: "Beschreibung", seller: "Verkäufer", profile: "Profil",
    listingContact: "Verkäufer kontaktieren", listingOffer: "Angebot machen", listingOfferSent: "Angebot gesendet!",
    listingChatErr: "Chat-Fehler", listingNotFound: "Anzeige nicht gefunden", listingLoadErr: "Ladefehler",
    listingCondition: "Zustand",
    myFavorites: "Meine Favoriten", myOrders: "Meine Bestellungen", myWallet: "FM-Geldbörse", myKyc: "Identität (KYC)",
    myReviews: "Bewertungen", mySettings: "Einstellungen", myListings: "Meine Anzeigen",
    seeAll: "Alle sehen", logout: "Abmelden", logoutTitle: "Abmelden",
    logoutMsg: "Möchten Sie sich wirklich abmelden?",
    listingsCount: "Anzeigen", verified: "Verifiziert", notVerified: "Nicht verifiziert",
    rating: "Bewertung", agentProfile: "Agentenprofil",
    sAccount: "Konto", sEditProfile: "Profil bearbeiten",
    sEditProfileHint: "Öffnen Sie die FlexaMarket-Website, um Ihr Profil zu bearbeiten.",
    sPasswordSecurity: "Passwort & Sicherheit",
    sPasswordSecurityHint: "Gehen Sie zu Einstellungen → Sicherheit auf FlexaMarket, um Ihr Passwort zu ändern.",
    sKyc: "Identitätsverifizierung (KYC)", sPhone: "Telefon & OTP",
    sPhoneHint: "Kontaktieren Sie den FlexaMarket-Support, um Ihre Telefonnummer zu ändern.",
    sPreferences: "Einstellungen", sNotifications: "Benachrichtigungen",
    sNotifOn: "Aktiviert", sNotifOff: "Deaktiviert", sLanguage: "Sprache",
    sAppearance: "Erscheinungsbild", sDarkMode: "Dunkelmodus",
    sFinances: "Finanzen", sWalletFM: "FM-Geldbörse",
    sPayoutAccount: "Verkäufer-Zahlungskonto",
    sPayoutAccountHint: "Konfigurieren Sie Ihr MonCash- und Bankkonto in den FlexaMarket-Einstellungen.",
    sSupport: "Support", sHelpSupport: "Hilfe & Support",
    sHelpSupportHint: "Senden Sie eine E-Mail an support@flexamarket.com oder nutzen Sie den Support-Bereich.",
    sTerms: "Nutzungsbedingungen",
    sTermsHint: "Besuchen Sie flexamarket.com/terms, um die Nutzungsbedingungen zu lesen.",
    sAbout: "Über FlexaMarket",
    sAboutMsg: "Der erste Kauf- & Verkaufs-Marktplatz in der Karibik.\n\nVersion 1.0.0\n© 2026 FlexaMarket",
    sLogout: "Abmelden",
    ordersTitle: "Bestellungen", ordersBuying: "Käufe", ordersSelling: "Verkäufe",
    noOrders: "Keine Bestellungen", noOrdersHint: "Ihre Bestellungen erscheinen hier, wenn Sie kaufen oder verkaufen.",
    walletTitle: "FM-Geldbörse", realBalance: "Echtes Guthaben", promoBalance: "Promo",
    unlockedBalance: "Entsperrt", recharge: "Aufladen", send: "Senden", withdraw: "Abheben",
    noTransactions: "Keine Transaktionen", noTransactionsHint: "Ihre Transaktionen erscheinen hier.",
    txHistory: "Transaktionsverlauf",
    rechargeTitle: "Geldbörse aufladen",
    rechargeMsg: "Senden Sie MonCash an +509 40-40-1234 und geben Sie die Transaktionsnummer im Support ein.",
    sendTitle: "Geld senden",
    sendMsg: "Verwenden Sie den 'Senden'-Bereich auf FlexaMarket für P2P-Überweisungen.",
    withdrawTitle: "Abheben",
    withdrawMsg: "Kontaktieren Sie den Support, um eine Auszahlung zu beantragen.",
    kycTitle: "Identitätsverifizierung", kycApproved: "Identität verifiziert ✅",
    kycApprovedSub: "Ihr Konto ist verifiziert. Sie können alle Transaktionen ohne Limits durchführen.",
    kycPending: "Ausstehende Überprüfung",
    kycPendingSub: "Ihr Antrag wurde eingereicht. Der Admin überprüft ihn innerhalb von 24 Stunden.",
    kycRejected: "Antrag abgelehnt",
    kycInfoText: "Identitätsverifizierung ist für Überweisungen über 500 $ erforderlich.",
    kycSubmitting: "Wird eingereicht...", kycErrTitle: "Fehler",
    kycErrDocs: "Bitte laden Sie ein Dokumentfoto und ein Selfie hoch.",
    kycSubmitTitle: "Eingereicht!", kycSubmitMsg: "Ihr KYC wurde eingereicht. Admin überprüft es in 24 Stunden.",
    kycErrMsg: "Einreichung fehlgeschlagen. Bitte erneut versuchen.",
    kycDocType: "Dokumenttyp", kycNatId: "Personalausweis", kycPassport: "Reisepass",
    kycDrivingLicense: "Führerschein", kycDocFront: "Dokumentfoto",
    kycDocFrontHint: "Tippen Sie, um die Vorderseite des Dokuments hochzuladen", kycSelfie: "Selfie",
    kycSelfieHint: "Tippen Sie, um ein Selfie hochzuladen", kycSubmitBtn: "Verifizierung einreichen",
    inboxTitle: "Nachrichten", noConversations: "Keine Gespräche",
    noConvHint: "Tippen Sie auf eine Anzeige und kontaktieren Sie den Verkäufer.",
    sellTitle: "Anzeige erstellen", searchTitle: "Suchen",
    searchNoResults: "Keine Ergebnisse", searchHint: "Versuchen Sie ein anderes Stichwort.",
    chatOnline: "Online", notVerifiedKyc: "Nicht verifiziert",
    languagesTitle: "Sprachen", selectLanguage: "Sprache wählen",
    loginTitle: "Anmelden", loginSubtitle: "Willkommen zurück! Melden Sie sich an.",
    loginEmailPlaceholder: "sie@email.com", loginPassword: "Passwort",
    loginBtn: "Anmelden", loginOr: "oder", loginCreateBtn: "Konto erstellen",
    registerTitle: "Konto erstellen", registerSubtitle: "Treten Sie der FlexaMarket-Gemeinschaft bei.",
    registerFullName: "Vollständiger Name", registerFullNamePlaceholder: "Hans Müller",
    registerPasswordPlaceholder: "Mindestens 6 Zeichen",
    registerCountry: "Land", registerBtn: "Konto erstellen",
    errFillAll: "Bitte füllen Sie alle Pflichtfelder aus.",
    errPassword6: "Das Passwort muss mindestens 6 Zeichen lang sein.",
    errLoginFailed: "Anmeldung fehlgeschlagen", errRegisterFailed: "Registrierung fehlgeschlagen",
    errConnection: "Verbindungsfehler", alreadyAccount: "Haben Sie bereits ein Konto?",
  },

  hi: {
    tabHome: "होम", tabSearch: "खोजें", tabSell: "बेचें", tabMessages: "संदेश", tabProfile: "प्रोफाइल",
    back: "वापस", loading: "लोड हो रहा है...", cancel: "रद्द करें", save: "सहेजें", ok: "ठीक है", greeting: "नमस्ते",
    allCategories: "सभी", noListings: "कोई लिस्टिंग नहीं",
    sponsored: "प्रायोजित", description: "विवरण", seller: "विक्रेता", profile: "प्रोफाइल",
    listingContact: "विक्रेता से संपर्क करें", listingOffer: "ऑफर करें", listingOfferSent: "ऑफर भेजा!",
    listingChatErr: "चैट त्रुटि", listingNotFound: "लिस्टिंग नहीं मिली", listingLoadErr: "लोड त्रुटि",
    listingCondition: "स्थिति",
    myFavorites: "मेरे पसंदीदा", myOrders: "मेरे ऑर्डर", myWallet: "FM वॉलेट", myKyc: "पहचान (KYC)",
    myReviews: "समीक्षाएं", mySettings: "सेटिंग्स", myListings: "मेरी लिस्टिंग",
    seeAll: "सभी देखें", logout: "साइन आउट", logoutTitle: "साइन आउट",
    logoutMsg: "क्या आप वाकई साइन आउट करना चाहते हैं?",
    listingsCount: "लिस्टिंग", verified: "सत्यापित", notVerified: "असत्यापित",
    rating: "रेटिंग", agentProfile: "एजेंट प्रोफाइल",
    sAccount: "खाता", sEditProfile: "प्रोफाइल संपादित करें",
    sEditProfileHint: "प्रोफाइल संपादित करने के लिए FlexaMarket वेबसाइट खोलें।",
    sPasswordSecurity: "पासवर्ड और सुरक्षा",
    sPasswordSecurityHint: "पासवर्ड बदलने के लिए FlexaMarket पर सेटिंग्स → सुरक्षा में जाएं।",
    sKyc: "पहचान सत्यापन (KYC)", sPhone: "फोन और OTP",
    sPhoneHint: "फोन नंबर बदलने के लिए FlexaMarket सपोर्ट से संपर्क करें।",
    sPreferences: "प्राथमिकताएं", sNotifications: "सूचनाएं",
    sNotifOn: "सक्रिय", sNotifOff: "अक्षम", sLanguage: "भाषा",
    sAppearance: "दिखावट", sDarkMode: "डार्क मोड",
    sFinances: "वित्त", sWalletFM: "FM वॉलेट",
    sPayoutAccount: "विक्रेता भुगतान खाता",
    sPayoutAccountHint: "FlexaMarket सेटिंग्स में MonCash और बैंक खाता कॉन्फ़िगर करें।",
    sSupport: "सहायता", sHelpSupport: "सहायता",
    sHelpSupportHint: "support@flexamarket.com पर ईमेल करें या वेबसाइट पर सपोर्ट अनुभाग का उपयोग करें।",
    sTerms: "सेवा की शर्तें",
    sTermsHint: "शर्तें पढ़ने के लिए flexamarket.com/terms पर जाएं।",
    sAbout: "FlexaMarket के बारे में",
    sAboutMsg: "कैरिबियन का पहला खरीद-बिक्री मार्केटप्लेस।\n\nवर्शन 1.0.0\n© 2026 FlexaMarket",
    sLogout: "साइन आउट",
    ordersTitle: "ऑर्डर", ordersBuying: "खरीदारी", ordersSelling: "बिक्री",
    noOrders: "कोई ऑर्डर नहीं", noOrdersHint: "खरीदने या बेचने पर आपके ऑर्डर यहां दिखेंगे।",
    walletTitle: "FM वॉलेट", realBalance: "वास्तविक शेष", promoBalance: "प्रोमो",
    unlockedBalance: "अनलॉक", recharge: "रीचार्ज", send: "भेजें", withdraw: "निकालें",
    noTransactions: "कोई लेनदेन नहीं", noTransactionsHint: "आपके लेनदेन यहां दिखेंगे।",
    txHistory: "लेनदेन इतिहास",
    rechargeTitle: "वॉलेट रीचार्ज",
    rechargeMsg: "+509 40-40-1234 पर MonCash भेजें और सपोर्ट में लेनदेन नंबर दर्ज करें।",
    sendTitle: "पैसे भेजें",
    sendMsg: "P2P ट्रांसफर के लिए FlexaMarket पर 'भेजें' अनुभाग का उपयोग करें।",
    withdrawTitle: "निकासी",
    withdrawMsg: "निकासी के लिए सपोर्ट से संपर्क करें।",
    kycTitle: "पहचान सत्यापन", kycApproved: "पहचान सत्यापित ✅",
    kycApprovedSub: "आपका खाता सत्यापित है। आप सभी लेनदेन बिना सीमा के कर सकते हैं।",
    kycPending: "समीक्षाधीन",
    kycPendingSub: "आपका आवेदन जमा हो गया। एडमिन 24 घंटे में समीक्षा करेगा।",
    kycRejected: "आवेदन अस्वीकृत",
    kycInfoText: "$500 से अधिक ट्रांसफर के लिए पहचान सत्यापन आवश्यक है।",
    kycSubmitting: "जमा हो रहा है...", kycErrTitle: "त्रुटि",
    kycErrDocs: "कृपया ID फोटो और सेल्फी अपलोड करें।",
    kycSubmitTitle: "जमा!", kycSubmitMsg: "आपका KYC जमा हो गया। एडमिन 24 घंटे में समीक्षा करेगा।",
    kycErrMsg: "सबमिशन विफल। फिर प्रयास करें।",
    kycDocType: "दस्तावेज़ प्रकार", kycNatId: "राष्ट्रीय ID", kycPassport: "पासपोर्ट",
    kycDrivingLicense: "ड्राइविंग लाइसेंस", kycDocFront: "ID फोटो",
    kycDocFrontHint: "ID का अग्र भाग अपलोड करने के लिए टैप करें", kycSelfie: "सेल्फी",
    kycSelfieHint: "सेल्फी अपलोड करने के लिए टैप करें", kycSubmitBtn: "सत्यापन जमा करें",
    inboxTitle: "संदेश", noConversations: "कोई बातचीत नहीं",
    noConvHint: "शुरू करने के लिए किसी लिस्टिंग पर टैप करें और विक्रेता से संपर्क करें।",
    sellTitle: "लिस्टिंग बनाएं", searchTitle: "खोजें",
    searchNoResults: "कोई परिणाम नहीं", searchHint: "दूसरा कीवर्ड आज़माएं।",
    chatOnline: "ऑनलाइन", notVerifiedKyc: "असत्यापित",
    languagesTitle: "भाषाएं", selectLanguage: "अपनी भाषा चुनें",
    loginTitle: "साइन इन करें", loginSubtitle: "वापस स्वागत है! अपने खाते में प्रवेश करें।",
    loginEmailPlaceholder: "aap@email.com", loginPassword: "पासवर्ड",
    loginBtn: "साइन इन करें", loginOr: "या", loginCreateBtn: "खाता बनाएं",
    registerTitle: "खाता बनाएं", registerSubtitle: "FlexaMarket समुदाय से जुड़ें।",
    registerFullName: "पूरा नाम", registerFullNamePlaceholder: "राज शर्मा",
    registerPasswordPlaceholder: "कम से कम 6 अक्षर",
    registerCountry: "देश", registerBtn: "खाता बनाएं",
    errFillAll: "कृपया सभी आवश्यक फ़ील्ड भरें।",
    errPassword6: "पासवर्ड में कम से कम 6 अक्षर होने चाहिए।",
    errLoginFailed: "साइन इन विफल", errRegisterFailed: "पंजीकरण विफल",
    errConnection: "कनेक्शन त्रुटि", alreadyAccount: "पहले से खाता है?",
  },

  fil: {
    tabHome: "Tahanan", tabSearch: "Maghanap", tabSell: "Ibenta", tabMessages: "Mga Mensahe", tabProfile: "Profile",
    back: "Bumalik", loading: "Naglo-load...", cancel: "Kanselahin", save: "I-save", ok: "OK", greeting: "Kumusta",
    allCategories: "Lahat", noListings: "Walang listahan",
    sponsored: "Sponsor", description: "Paglalarawan", seller: "Nagbebenta", profile: "Profile",
    listingContact: "Makipag-ugnayan sa Nagbebenta", listingOffer: "Mag-alok", listingOfferSent: "Naipadala ang alok!",
    listingChatErr: "Error sa chat", listingNotFound: "Hindi nahanap ang listahan", listingLoadErr: "Error sa pag-load",
    listingCondition: "Kondisyon",
    myFavorites: "Mga Paborito Ko", myOrders: "Mga Order Ko", myWallet: "FM Wallet", myKyc: "Pagkakakilanlan (KYC)",
    myReviews: "Mga Review", mySettings: "Mga Setting", myListings: "Mga Listahan Ko",
    seeAll: "Tingnan lahat", logout: "Mag-sign out", logoutTitle: "Mag-sign out",
    logoutMsg: "Sigurado ka bang gusto mong mag-sign out?",
    listingsCount: "Mga Listahan", verified: "Na-verify", notVerified: "Hindi na-verify",
    rating: "Rating", agentProfile: "Profile ng Agent",
    sAccount: "Account", sEditProfile: "I-edit ang Profile",
    sEditProfileHint: "Buksan ang FlexaMarket website para i-edit ang iyong profile.",
    sPasswordSecurity: "Password at Seguridad",
    sPasswordSecurityHint: "Pumunta sa Settings → Seguridad sa FlexaMarket para baguhin ang password.",
    sKyc: "Pagpapatunay ng Pagkakakilanlan (KYC)", sPhone: "Telepono at OTP",
    sPhoneHint: "Makipag-ugnayan sa suporta ng FlexaMarket para baguhin ang numero ng telepono.",
    sPreferences: "Mga Kagustuhan", sNotifications: "Mga Notipikasyon",
    sNotifOn: "Naka-enable", sNotifOff: "Naka-disable", sLanguage: "Wika",
    sAppearance: "Hitsura", sDarkMode: "Dark mode",
    sFinances: "Pananalapi", sWalletFM: "FM Wallet",
    sPayoutAccount: "Seller Payout Account",
    sPayoutAccountHint: "I-configure ang MonCash at bank account sa FlexaMarket Settings.",
    sSupport: "Suporta", sHelpSupport: "Tulong at Suporta",
    sHelpSupportHint: "Mag-email sa support@flexamarket.com o gamitin ang seksyon ng Suporta.",
    sTerms: "Mga Tuntunin ng Serbisyo",
    sTermsHint: "Bisitahin ang flexamarket.com/terms para basahin ang mga tuntunin.",
    sAbout: "Tungkol sa FlexaMarket",
    sAboutMsg: "Unang marketplace ng pagbili at pagbebenta sa Caribbean.\n\nBersyon 1.0.0\n© 2026 FlexaMarket",
    sLogout: "Mag-sign out",
    ordersTitle: "Mga Order", ordersBuying: "Pagbibili", ordersSelling: "Pagbebenta",
    noOrders: "Walang order", noOrdersHint: "Ang iyong mga order ay lalabas dito kapag bumili o nagbenta.",
    walletTitle: "FM Wallet", realBalance: "Totoong Balanse", promoBalance: "Promo",
    unlockedBalance: "Na-unlock", recharge: "Mag-recharge", send: "Ipadala", withdraw: "Mag-withdraw",
    noTransactions: "Walang transaksyon", noTransactionsHint: "Ang iyong mga transaksyon ay lalabas dito.",
    txHistory: "Kasaysayan ng Transaksyon",
    rechargeTitle: "Mag-recharge ng Wallet",
    rechargeMsg: "Magpadala ng MonCash sa +509 40-40-1234 at ilagay ang numero ng transaksyon sa suporta.",
    sendTitle: "Magpadala ng Pera",
    sendMsg: "Gamitin ang seksyong 'Ipadala' sa FlexaMarket para sa P2P na paglilipat.",
    withdrawTitle: "Mag-withdraw",
    withdrawMsg: "Makipag-ugnayan sa suporta para humiling ng withdrawal.",
    kycTitle: "Pagpapatunay ng Pagkakakilanlan", kycApproved: "Na-verify ang Pagkakakilanlan ✅",
    kycApprovedSub: "Na-verify ang iyong account. Maaari kang makumpleto ang lahat ng transaksyon.",
    kycPending: "Naghihintay ng Pagsusuri",
    kycPendingSub: "Naisumite na ang iyong aplikasyon. Susuriin ng admin sa loob ng 24 oras.",
    kycRejected: "Tinanggihan ang Aplikasyon",
    kycInfoText: "Kailangan ang pagpapatunay ng pagkakakilanlan para sa mga transfer na higit sa $500.",
    kycSubmitting: "Isinusumite...", kycErrTitle: "Error",
    kycErrDocs: "Mag-upload ng larawan ng ID at selfie.",
    kycSubmitTitle: "Naisumite!", kycSubmitMsg: "Naisumite ang iyong KYC. Susuriin ng admin sa loob ng 24 oras.",
    kycErrMsg: "Nabigo ang pagsusumite. Subukan ulit.",
    kycDocType: "Uri ng Dokumento", kycNatId: "National ID", kycPassport: "Pasaporte",
    kycDrivingLicense: "Driver's License", kycDocFront: "Larawan ng ID",
    kycDocFrontHint: "I-tap para mag-upload ng harap ng ID", kycSelfie: "Selfie",
    kycSelfieHint: "I-tap para mag-upload ng selfie", kycSubmitBtn: "Isumite ang Pagpapatunay",
    inboxTitle: "Mga Mensahe", noConversations: "Walang pag-uusap",
    noConvHint: "Mag-tap sa listahan at makipag-ugnayan sa nagbebenta para magsimula.",
    sellTitle: "Gumawa ng Listahan", searchTitle: "Maghanap",
    searchNoResults: "Walang resulta", searchHint: "Subukan ang ibang keyword.",
    chatOnline: "Online", notVerifiedKyc: "Hindi na-verify",
    languagesTitle: "Mga Wika", selectLanguage: "Piliin ang iyong wika",
    loginTitle: "Mag-sign in", loginSubtitle: "Maligayang pagbabalik! Pumasok sa iyong account.",
    loginEmailPlaceholder: "ikaw@email.com", loginPassword: "Password",
    loginBtn: "Mag-sign in", loginOr: "o", loginCreateBtn: "Gumawa ng account",
    registerTitle: "Gumawa ng Account", registerSubtitle: "Sumali sa komunidad ng FlexaMarket.",
    registerFullName: "Buong Pangalan", registerFullNamePlaceholder: "Juan dela Cruz",
    registerPasswordPlaceholder: "Hindi bababa sa 6 na karakter",
    registerCountry: "Bansa", registerBtn: "Gumawa ng Account",
    errFillAll: "Pakipunan ang lahat ng kinakailangang field.",
    errPassword6: "Ang password ay dapat may hindi bababa sa 6 na karakter.",
    errLoginFailed: "Nabigo ang pag-sign in", errRegisterFailed: "Nabigo ang pagpaparehistro",
    errConnection: "Error sa koneksyon", alreadyAccount: "Mayroon ka nang account?",
  },

  ha: {
    tabHome: "Gida", tabSearch: "Bincika", tabSell: "Siyar", tabMessages: "Saƙonni", tabProfile: "Bayani",
    back: "Komawa", loading: "Ana lodawa...", cancel: "Soke", save: "Ajiye", ok: "Yawwa", greeting: "Sannu",
    allCategories: "Duka", noListings: "Babu tallace-tallace",
    sponsored: "Mai tallafi", description: "Bayanai", seller: "Mai siyarwa", profile: "Bayani",
    listingContact: "Tuntuɓi mai siyarwa", listingOffer: "Yi tayin", listingOfferSent: "An aika tayin!",
    listingChatErr: "Kuskuren chat", listingNotFound: "Ba a sami tallace ba", listingLoadErr: "Kuskuren lodawa",
    listingCondition: "Yanayin",
    myFavorites: "Abubuwan da na fi so", myOrders: "Umarnina", myWallet: "FM Walat", myKyc: "Tabbatarwa (KYC)",
    myReviews: "Sake nazari", mySettings: "Saituna", myListings: "Tallacena",
    seeAll: "Duba duka", logout: "Fita", logoutTitle: "Fita",
    logoutMsg: "Kun tabbata kuna son fita?",
    listingsCount: "Tallace-tallace", verified: "An tabbatar", notVerified: "Ba a tabbatar ba",
    rating: "Matsayi", agentProfile: "Bayani na Wakili",
    sAccount: "Asusun", sEditProfile: "Gyara bayani",
    sEditProfileHint: "Buɗe gidan yanar gizon FlexaMarket don gyara bayaninka.",
    sPasswordSecurity: "Kalmar sirri & Tsaro",
    sPasswordSecurityHint: "Je zuwa Saituna → Tsaro a FlexaMarket don canza kalmar sirri.",
    sKyc: "Tabbatar da Asali (KYC)", sPhone: "Waya & OTP",
    sPhoneHint: "Tuntuɓi tallafi na FlexaMarket don canza lambar waya.",
    sPreferences: "Zaɓuɓɓuka", sNotifications: "Sanarwa",
    sNotifOn: "An kunna", sNotifOff: "An kashe", sLanguage: "Harshe",
    sAppearance: "Bayyanawa", sDarkMode: "Yanayin duhu",
    sFinances: "Kuɗi", sWalletFM: "FM Walat",
    sPayoutAccount: "Asusun biyan kuɗi",
    sPayoutAccountHint: "Saita asusun MonCash da banki a saituna na FlexaMarket.",
    sSupport: "Tallafi", sHelpSupport: "Taimako",
    sHelpSupportHint: "Aika imel zuwa support@flexamarket.com ko yi amfani da sashen tallafi.",
    sTerms: "Sharuddan amfani",
    sTermsHint: "Je zuwa flexamarket.com/terms don karanta sharuddan.",
    sAbout: "Game da FlexaMarket",
    sAboutMsg: "Kayan kasuwa na farko na siye da siyarwa a Caribbean.\n\nSigar 1.0.0\n© 2026 FlexaMarket",
    sLogout: "Fita",
    ordersTitle: "Umarni", ordersBuying: "Saye", ordersSelling: "Siyarwa",
    noOrders: "Babu umarni", noOrdersHint: "Umarnin ku za nan idan kun saye ko sayar.",
    walletTitle: "FM Walat", realBalance: "Ainihin Ragamar", promoBalance: "Promo",
    unlockedBalance: "An buɗe", recharge: "Caji", send: "Aika", withdraw: "Fitar",
    noTransactions: "Babu ciniki", noTransactionsHint: "Cinikinka za su bayyana nan.",
    txHistory: "Tarihin ciniki",
    rechargeTitle: "Caji Walat",
    rechargeMsg: "Aika MonCash zuwa +509 40-40-1234 sannan ka shigar da lambar ciniki a tallafi.",
    sendTitle: "Aika kuɗi",
    sendMsg: "Yi amfani da sashen 'Aika' a FlexaMarket don canja kuɗi P2P.",
    withdrawTitle: "Fitar kuɗi",
    withdrawMsg: "Tuntuɓi tallafi don neman fitar kuɗi.",
    kycTitle: "Tabbatar da asali", kycApproved: "An tabbatar da asali ✅",
    kycApprovedSub: "An tabbatar da asusunka. Zaka iya yin duk ciniki ba iyaka.",
    kycPending: "Yana jiran dubawa",
    kycPendingSub: "An gabatar da bukatarka. Admin zai duba a cikin awanni 24.",
    kycRejected: "An ƙi bukata",
    kycInfoText: "Tabbatar da asali ya zama wajibi don canja kuɗi sama da $500.",
    kycSubmitting: "Ana gabatarwa...", kycErrTitle: "Kuskure",
    kycErrDocs: "Da fatan a loda hoto na takarda da selfie.",
    kycSubmitTitle: "An gabatar!", kycSubmitMsg: "An gabatar da KYC ɗinka. Admin zai duba a cikin awanni 24.",
    kycErrMsg: "Gabatarwa ta kasa. Gwada sake.",
    kycDocType: "Nau'in takarda", kycNatId: "Katin shaida", kycPassport: "Fasfo",
    kycDrivingLicense: "Lasisi", kycDocFront: "Hoto na takarda",
    kycDocFrontHint: "Danna don loda hoto na gaba", kycSelfie: "Selfie",
    kycSelfieHint: "Danna don loda selfie", kycSubmitBtn: "Gabatar da tabbatarwa",
    inboxTitle: "Saƙonni", noConversations: "Babu tattaunawa",
    noConvHint: "Danna tallacen don tuntuɓi mai siyarwa don fara.",
    sellTitle: "Ƙirƙiri tallace", searchTitle: "Bincika",
    searchNoResults: "Babu sakamako", searchHint: "Gwada wani kalma.",
    chatOnline: "Yana kan layi", notVerifiedKyc: "Ba a tabbatar ba",
    languagesTitle: "Harsunan", selectLanguage: "Zaɓi harsheka",
    loginTitle: "Shiga", loginSubtitle: "Barka da dawowa! Shiga asusunka.",
    loginEmailPlaceholder: "kai@email.com", loginPassword: "Kalmar sirri",
    loginBtn: "Shiga", loginOr: "ko", loginCreateBtn: "Ƙirƙiri asusun",
    registerTitle: "Ƙirƙiri Asusun", registerSubtitle: "Shiga cikin al'ummar FlexaMarket.",
    registerFullName: "Cikakken suna", registerFullNamePlaceholder: "Aminu Musa",
    registerPasswordPlaceholder: "Aƙalla harafi 6",
    registerCountry: "Ƙasa", registerBtn: "Ƙirƙiri Asusun",
    errFillAll: "Da fatan a cika duk filayen da ake buƙata.",
    errPassword6: "Kalmar sirri dole ta kasance da aƙalla harafi 6.",
    errLoginFailed: "Shiga ya kasa", errRegisterFailed: "Rijista ta kasa",
    errConnection: "Kuskuren haɗi", alreadyAccount: "Kuna da asusun?",
  },

  zu: {
    tabHome: "Ikhaya", tabSearch: "Sesha", tabSell: "Thengisa", tabMessages: "Imiyalezo", tabProfile: "Iphrofayili",
    back: "Emuva", loading: "Iyalayisha...", cancel: "Khansela", save: "Londoloza", ok: "KULUNGILE", greeting: "Sawubona",
    allCategories: "Konke", noListings: "Ayikho imikhangiso",
    sponsored: "Ukukhuthazwa", description: "Incazelo", seller: "Umthengisi", profile: "Iphrofayili",
    listingContact: "Xhumana nomthengisi", listingOffer: "Yenza umnikelo", listingOfferSent: "Umnikelo uthunyelwe!",
    listingChatErr: "Iphutha le-chat", listingNotFound: "Ayitholakali imikhangiso", listingLoadErr: "Iphutha lokukhokhela",
    listingCondition: "Isimo",
    myFavorites: "Izintandokazi Zami", myOrders: "Izimemezelo Zami", myWallet: "FM Wallet", myKyc: "Isithunzi (KYC)",
    myReviews: "Izibuyekezo", mySettings: "Izilungiselelo", myListings: "Imikhangiso Yami",
    seeAll: "Buka konke", logout: "Phuma", logoutTitle: "Phuma",
    logoutMsg: "Uqinisekile ukuthi ufuna ukuphuma?",
    listingsCount: "Imikhangiso", verified: "Kufinyelelwe", notVerified: "Akufikelelwanga",
    rating: "Isilinganiso", agentProfile: "Iphrofayili ye-ejenti",
    sAccount: "I-akhawunti", sEditProfile: "Hlela iphrofayili",
    sEditProfileHint: "Vula iwebhusayithi ye-FlexaMarket ukuze uhlele iphrofayili yakho.",
    sPasswordSecurity: "Iphasiwedi & Ukuphepha",
    sPasswordSecurityHint: "Yiya ku-Settings → Ukuphepha ku-FlexaMarket ukuze ushintshe iphasiwedi.",
    sKyc: "Ukuqinisekisa Ubunikazi (KYC)", sPhone: "Ucingo & OTP",
    sPhoneHint: "Xhumana ne-FlexaMarket support ukuze ushintshe inombolo yocingo.",
    sPreferences: "Izintandokazi", sNotifications: "Izaziso",
    sNotifOn: "Kuvuliwe", sNotifOff: "Kuvaliwe", sLanguage: "Ulimi",
    sAppearance: "Isimo", sDarkMode: "Imodi emnyama",
    sFinances: "Imali", sWalletFM: "FM Wallet",
    sPayoutAccount: "I-akhawunti yokukhokha",
    sPayoutAccountHint: "Lungisa i-MonCash ne-akhawunti ye-bhangi ku-FlexaMarket Settings.",
    sSupport: "Usizo", sHelpSupport: "Usizo",
    sHelpSupportHint: "Thumela i-imeyili ku-support@flexamarket.com noma usebenzise isigaba Sosizo.",
    sTerms: "Imigomo",
    sTermsHint: "Vakashela i-flexamarket.com/terms ukuze ufunde imigomo.",
    sAbout: "Mayelana ne-FlexaMarket",
    sAboutMsg: "Indawo yokuthenga nokukhokha yokuqala eCaribbean.\n\nUhlelo 1.0.0\n© 2026 FlexaMarket",
    sLogout: "Phuma",
    ordersTitle: "Izimemezelo", ordersBuying: "Ukuthenga", ordersSelling: "Ukuthengisa",
    noOrders: "Ayikho izimemezelo", noOrdersHint: "Izimemezelo zakho zizovela lapha lapho uthenga noma uthengisa.",
    walletTitle: "FM Wallet", realBalance: "Ibhalansi Yangempela", promoBalance: "Promo",
    unlockedBalance: "Kuvuliwe", recharge: "Gcwalisa", send: "Thumela", withdraw: "Khipha",
    noTransactions: "Azikho izinkokhelo", noTransactionsHint: "Izinkokhelo zakho zizovela lapha.",
    txHistory: "Umlando Wezinkokhelo",
    rechargeTitle: "Gcwalisa i-Wallet",
    rechargeMsg: "Thumela i-MonCash ku-+509 40-40-1234 bese ufaka inombolo yenkokhelo ku-support.",
    sendTitle: "Thumela Imali",
    sendMsg: "Sebenzisa isigaba 'Thumela' ku-FlexaMarket ukwenza ukudlulisela kwe-P2P.",
    withdrawTitle: "Khipha Imali",
    withdrawMsg: "Xhumana ne-support ukuze ucele ukukhipha imali.",
    kycTitle: "Ukuqinisekisa Ubunikazi", kycApproved: "Ubunikazi Buqinisekisiwe ✅",
    kycApprovedSub: "I-akhawunti yakho iqinisekisiwe. Ungenza yonke imisebenzi ngaphandle kwemikhawulo.",
    kycPending: "Kulindele Ukubuyekezwa",
    kycPendingSub: "Isicelo sakho sithunyelwe. I-admin izosibuyekeza ngamahora angu-24.",
    kycRejected: "Isicelo Sanqanyulwa",
    kycInfoText: "Ukuqinisekisa kuyadingeka kokudilulelwa okuphezulu kuka-$500.",
    kycSubmitting: "Kuthunyelwa...", kycErrTitle: "Iphutha",
    kycErrDocs: "Sicela ulayishe isithombe se-ID ne-selfie.",
    kycSubmitTitle: "Kuthunyelwe!", kycSubmitMsg: "I-KYC yakho ithunyelwe. I-admin izobuyekeza ngamahora angu-24.",
    kycErrMsg: "Ukuthumela kuhlulekile. Zama futhi.",
    kycDocType: "Uhlobo Lwedokhumenti", kycNatId: "I-ID Yezwe", kycPassport: "Iphasipoti",
    kycDrivingLicense: "Ilayisense", kycDocFront: "Isithombe se-ID",
    kycDocFrontHint: "Thepha ukuze ulayishe ngaphambili kwe-ID", kycSelfie: "I-selfie",
    kycSelfieHint: "Thepha ukuze ulayishe i-selfie", kycSubmitBtn: "Thumela Ukuqinisekisa",
    inboxTitle: "Imiyalezo", noConversations: "Azikho izingxoxo",
    noConvHint: "Chofoza imikhangiso bese uxhumana nomthengisi ukuze uqale.",
    sellTitle: "Dala Imikhangiso", searchTitle: "Sesha",
    searchNoResults: "Awekho imiphumela", searchHint: "Zama igama elinye.",
    chatOnline: "Ku inthanethi", notVerifiedKyc: "Akufinyelele",
    languagesTitle: "Izilimi", selectLanguage: "Khetha ulimi lwakho",
    loginTitle: "Ngena", loginSubtitle: "Wamukelekile futhi! Ngena ku-akhawunti yakho.",
    loginEmailPlaceholder: "wena@email.com", loginPassword: "Iphasiwedi",
    loginBtn: "Ngena", loginOr: "noma", loginCreateBtn: "Dala i-akhawunti",
    registerTitle: "Dala I-akhawunti", registerSubtitle: "Joyina umphakathi we-FlexaMarket.",
    registerFullName: "Igama eligcwele", registerFullNamePlaceholder: "Sipho Dlamini",
    registerPasswordPlaceholder: "Okungenani izinhlamvu ezi-6",
    registerCountry: "Izwe", registerBtn: "Dala I-akhawunti",
    errFillAll: "Sicela ugcwalise wonke amasimu adingekayo.",
    errPassword6: "Iphasiwedi kufanele ibe nezinhlamvu ezingekho ngaphansi kwe-6.",
    errLoginFailed: "Ukungena kuhlulekile", errRegisterFailed: "Ukubhalisa kuhlulekile",
    errConnection: "Iphutha lokuqhangaza", alreadyAccount: "Sewune i-akhawunti?",
  },

  af: {
    tabHome: "Tuis", tabSearch: "Soek", tabSell: "Verkoop", tabMessages: "Boodskappe", tabProfile: "Profiel",
    back: "Terug", loading: "Laai...", cancel: "Kanselleer", save: "Stoor", ok: "OK", greeting: "Hallo",
    allCategories: "Almal", noListings: "Geen lyste",
    sponsored: "Geborg", description: "Beskrywing", seller: "Verkoper", profile: "Profiel",
    listingContact: "Kontak Verkoper", listingOffer: "Maak 'n bod", listingOfferSent: "Bod gestuur!",
    listingChatErr: "Klets fout", listingNotFound: "Lys nie gevind", listingLoadErr: "Laai fout",
    listingCondition: "Toestand",
    myFavorites: "My Gunstelinge", myOrders: "My Bestellings", myWallet: "FM Beursie", myKyc: "Identiteit (KYC)",
    myReviews: "Resensies", mySettings: "Instellings", myListings: "My Lyste",
    seeAll: "Sien almal", logout: "Meld af", logoutTitle: "Meld af",
    logoutMsg: "Is jy seker jy wil afmeld?",
    listingsCount: "Lyste", verified: "Geverifieer", notVerified: "Nie geverifieer",
    rating: "Gradering", agentProfile: "Agentprofiel",
    sAccount: "Rekening", sEditProfile: "Wysig profiel",
    sEditProfileHint: "Maak die FlexaMarket-webwerf oop om jou profiel te wysig.",
    sPasswordSecurity: "Wagwoord & Sekuriteit",
    sPasswordSecurityHint: "Gaan na Instellings → Sekuriteit op FlexaMarket om jou wagwoord te verander.",
    sKyc: "Identiteitsverifikasie (KYC)", sPhone: "Telefoon & OTP",
    sPhoneHint: "Kontak FlexaMarket-ondersteuning om jou telefoonnommer te verander.",
    sPreferences: "Voorkeure", sNotifications: "Kennisgewings",
    sNotifOn: "Geaktiveer", sNotifOff: "Gedeaktiveer", sLanguage: "Taal",
    sAppearance: "Voorkoms", sDarkMode: "Donker modus",
    sFinances: "Finansies", sWalletFM: "FM Beursie",
    sPayoutAccount: "Verkoper betalingsrekening",
    sPayoutAccountHint: "Stel MonCash en bankrekening op in FlexaMarket Instellings.",
    sSupport: "Ondersteuning", sHelpSupport: "Hulp",
    sHelpSupportHint: "Stuur 'n e-pos na support@flexamarket.com of gebruik die Ondersteuningsafdeling.",
    sTerms: "Gebruiksvoorwaardes",
    sTermsHint: "Besoek flexamarket.com/terms om die voorwaardes te lees.",
    sAbout: "Oor FlexaMarket",
    sAboutMsg: "Die eerste koop- en verkoopmark in die Karibiese Eilande.\n\nWeergawe 1.0.0\n© 2026 FlexaMarket",
    sLogout: "Meld af",
    ordersTitle: "Bestellings", ordersBuying: "Koop", ordersSelling: "Verkoop",
    noOrders: "Geen bestellings", noOrdersHint: "Jou bestellings sal hier verskyn wanneer jy koop of verkoop.",
    walletTitle: "FM Beursie", realBalance: "Werklike Saldo", promoBalance: "Promo",
    unlockedBalance: "Ontsluit", recharge: "Herlaai", send: "Stuur", withdraw: "Onttrek",
    noTransactions: "Geen transaksies", noTransactionsHint: "Jou transaksies sal hier verskyn.",
    txHistory: "Transaksiegeskiedenis",
    rechargeTitle: "Herlaai Beursie",
    rechargeMsg: "Stuur MonCash na +509 40-40-1234 en voer die transaksienommer in by ondersteuning.",
    sendTitle: "Stuur Geld",
    sendMsg: "Gebruik die 'Stuur'-afdeling op FlexaMarket vir P2P-oordragte.",
    withdrawTitle: "Onttrek Geld",
    withdrawMsg: "Kontak ondersteuning om 'n onttrekking aan te vra.",
    kycTitle: "Identiteitsverifikasie", kycApproved: "Identiteit Geverifieer ✅",
    kycApprovedSub: "Jou rekening is geverifieer. Jy kan alle transaksies sonder beperkings voltooi.",
    kycPending: "Hangende Hersiening",
    kycPendingSub: "Jou aansoek is ingedien. Die admin sal dit binne 24 uur hersien.",
    kycRejected: "Aansoek verwerp",
    kycInfoText: "Identiteitsverifikasie is vereis vir oordragte van meer as $500.",
    kycSubmitting: "Word ingedien...", kycErrTitle: "Fout",
    kycErrDocs: "Laai asseblief 'n ID-foto en selfie op.",
    kycSubmitTitle: "Ingedien!", kycSubmitMsg: "Jou KYC is ingedien. Admin sal dit binne 24 uur hersien.",
    kycErrMsg: "Indiening misluk. Probeer weer.",
    kycDocType: "Dokumenttipe", kycNatId: "Nasionale ID", kycPassport: "Paspoort",
    kycDrivingLicense: "Rybewys", kycDocFront: "ID Foto",
    kycDocFrontHint: "Tik om die voorkant van jou ID op te laai", kycSelfie: "Selfie",
    kycSelfieHint: "Tik om 'n selfie op te laai", kycSubmitBtn: "Indien verifikasie",
    inboxTitle: "Boodskappe", noConversations: "Geen gesprekke",
    noConvHint: "Tik op 'n lys en kontak die verkoper om te begin.",
    sellTitle: "Skep lys", searchTitle: "Soek",
    searchNoResults: "Geen resultate", searchHint: "Probeer 'n ander sleutelwoord.",
    chatOnline: "Aanlyn", notVerifiedKyc: "Nie geverifieer",
    languagesTitle: "Tale", selectLanguage: "Kies jou taal",
    loginTitle: "Meld aan", loginSubtitle: "Welkom terug! Meld aan by jou rekening.",
    loginEmailPlaceholder: "jy@email.com", loginPassword: "Wagwoord",
    loginBtn: "Meld aan", loginOr: "of", loginCreateBtn: "Skep 'n rekening",
    registerTitle: "Skep Rekening", registerSubtitle: "Sluit aan by die FlexaMarket-gemeenskap.",
    registerFullName: "Volle naam", registerFullNamePlaceholder: "Jan van der Merwe",
    registerPasswordPlaceholder: "Minstens 6 karakters",
    registerCountry: "Land", registerBtn: "Skep Rekening",
    errFillAll: "Vul asseblief alle verpligte velde in.",
    errPassword6: "Wagwoord moet minstens 6 karakters hê.",
    errLoginFailed: "Aanmelding misluk", errRegisterFailed: "Registrasie misluk",
    errConnection: "Verbindingsfout", alreadyAccount: "Het jy reeds 'n rekening?",
  },
};

const ALL_LANGS = new Set<string>(["en","ht","fr","es","pt","de","hi","fil","ha","zu","af"]);

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => Promise<void>;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: async () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>("en");

  useEffect(() => {
    AsyncStorage.getItem(LANG_KEY)
      .then((v) => { if (v && ALL_LANGS.has(v)) setLangState(v as Lang); })
      .catch(() => { /* keep default language */ });
  }, []);

  const setLang = useCallback(async (l: Lang) => {
    setLangState(l);
    AsyncStorage.setItem(LANG_KEY, l).catch(() => {});
  }, []);

  const t = useCallback(
    (key: string): string => T[lang]?.[key] ?? T.en[key] ?? T.ht[key] ?? key,
    [lang]
  );

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
