import AsyncStorage from "@react-native-async-storage/async-storage";
import React, { createContext, useCallback, useContext, useEffect, useState } from "react";

export type Lang = "ht" | "fr";

const LANG_KEY = "flexa_lang";

const T: Record<Lang, Record<string, string>> = {
  ht: {
    tabHome: "Akèy",
    tabSearch: "Chèche",
    tabSell: "Vann",
    tabMessages: "Mesaj",
    tabProfile: "Pwofil",
    back: "Retounen",
    loading: "Ap chaje...",
    cancel: "Anile",
    save: "Sove",
    ok: "OK",
    greeting: "Bonjou",
    allCategories: "Tout",
    noListings: "Pa gen annons",
    kycTitle: "Verifikasyon Idantite",
    kycErrTitle: "Erè",
    kycErrDocs: "Ou bezwen telechaje foto dokiman ak selfie ou.",
    kycSubmitTitle: "Soumèt!",
    kycSubmitMsg: "Demann KYC ou soumèt. Admin pral revize li nan 24 èdtan.",
    kycErrMsg: "Echèk soumisyon. Eseye ankò.",
    kycDocType: "Tip Dokiman",
    kycNatId: "CIN",
    kycPassport: "Paspo",
    kycDrivingLicense: "Lisans",
    kycDocFront: "Foto Dokiman",
    kycDocFrontHint: "Pran foto recto dokiman",
    kycSelfie: "Selfie Avèk Dokiman",
    kycSelfieHint: "Selfie ou ak dokiman ou nan men ou",
    kycSubmitBtn: "Soumèt pou Verifikasyon",
    listingNotFound: "Annons pa jwenn",
    listingLoadErr: "Erè chajman",
    back: "Retounen",
    sponsored: "Sponsorisé",
    description: "Deskripsyon",
    seller: "Vandè",
    profile: "Pwofil",
    listingContact: "Mesaj",
    listingOffer: "Fè yon Òf",
    myFavorites: "Favori Mwen",
    myOrders: "Kòmand yo",
    myWallet: "Pòtfèy FM",
    myKyc: "Verifikasyon (KYC)",
    myReviews: "Evalyasyon",
    mySettings: "Paramèt",
    myListings: "Annons Mwen",
    seeAll: "Wè tout",
    logout: "Dekonekte",
    logoutTitle: "Dekonekte",
    logoutMsg: "Ou sèten ou vle dekonekte?",
    listingsCount: "Annons",
    verified: "Verifye",
    notVerified: "Pa verifye",
    rating: "Nòt",
    agentProfile: "Pwofil Ajan Mwen",
    sAccount: "Kont",
    sEditProfile: "Modifye Pwofil",
    sEditProfileHint: "Ouvè sit entènèt FlexaMarket pou modifye pwofil ou a.",
    sPasswordSecurity: "Modpas & Sekirite",
    sPasswordSecurityHint: "Ale nan Paramèt → Sekirite sou sit entènèt FlexaMarket pou chanje modpas ou.",
    sKyc: "Verifikasyon Idantite (KYC)",
    sPhone: "Telefòn & OTP",
    sPhoneHint: "Kontakte sipò FlexaMarket pou chanje nimewo telefòn ou.",
    sPreferences: "Preferans",
    sNotifications: "Notifikasyon",
    sNotifOn: "Aktif",
    sNotifOff: "Dezaktive",
    sLanguage: "Lang",
    sAppearance: "Aparans",
    sDarkMode: "Mode nwa",
    sFinances: "Finans",
    sWalletFM: "Pòtfèy FM",
    sPayoutAccount: "Kont Peman Vandè",
    sPayoutAccountHint: "Konfigire kont MonCash ak Bank ou nan Paramèt sou sit entènèt FlexaMarket.",
    sSupport: "Asistans",
    sHelpSupport: "Sipò",
    sHelpSupportHint: "Voye yon mesaj nan support@flexamarket.com oswa itilize seksyon Sipò sou sit entènèt la.",
    sTerms: "Kondisyon Itilizasyon",
    sTermsHint: "Ale sou flexamarket.com/terms pou li kondisyon itilizasyon yo.",
    sAbout: "Sou FlexaMarket",
    sAboutMsg: "Premye marketplace achte & vann ann Ayiti.\n\nVèsyon 1.0.0\n© 2026 FlexaMarket",
    sLogout: "Dekonekte",
    ordersTitle: "Kòmand yo",
    ordersBuying: "Achte",
    ordersSelling: "Vann",
    noOrders: "Pa gen kòmand",
    noOrdersHint: "Kòmand ou yo parèt isit lè ou achte oswa vann yon bagay.",
    walletTitle: "Pòtfèy FM",
    realBalance: "Balans Reyèl",
    promoBalance: "Promo",
    unlockedBalance: "Debloke",
    recharge: "Recharge",
    send: "Voye",
    withdraw: "Retire",
    noTransactions: "Pa gen tranzaksyon",
    noTransactionsHint: "Tranzaksyon ou yo parèt isit.",
    txHistory: "Istwa Tranzaksyon",
    rechargeTitle: "Recharge Pòtfèy",
    rechargeMsg: "Voye MonCash nan +509 40-40-1234 epi mete nimewo tranzaksyon ou a nan sipò pou konfirmasyon rapid.",
    sendTitle: "Voye Lajan",
    sendMsg: "Itilize seksyon 'Voye Lajan' sou sit entènèt FlexaMarket pou fè transfè P2P.",
    withdrawTitle: "Retire Lajan",
    withdrawMsg: "Kontakte sipò pou demande yon retrè.",
    kycTitle: "Verifikasyon Idantite",
    kycApproved: "Idantite Verifye ✅",
    kycApprovedSub: "Kont ou verifye. Ou ka fè tout tranzaksyon san limit.",
    kycPending: "Annatant Revizyon",
    kycPendingSub: "Demann ou soumèt. Admin pral revize li nan 24 èdtan.",
    kycRejected: "Demann Refize",
    kycInfoText: "Verifikasyon idantite obligatwa pou transfè plis pase $500 ak pou gwo tranzaksyon.",
    kycSubmitTitle: "Soumèt!",
    kycSubmitMsg: "Demann KYC ou soumèt. Admin pral revize li nan 24 èdtan.",
    kycErrTitle: "Erè",
    kycErrMsg: "Echèk soumisyon. Eseye ankò.",
    kycErrDocs: "Ou bezwen telechaje foto dokiman ak selfie ou.",
    kycSubmitting: "Ap soumèt...",
    kycDocType: "Tip Dokiman",
    kycNatId: "Kat Nasyonal",
    kycPassport: "Paspò",
    kycDrivingLicense: "Lisans Kondi",
    kycDocFront: "Foto Dokiman ID",
    kycDocFrontHint: "Klike pou telechaje foto devan ID ou a",
    kycSelfie: "Selfie",
    kycSelfieHint: "Klike pou telechaje yon selfie",
    kycSubmitBtn: "Soumèt Verifikasyon",
    listingNotFound: "Annons pa jwenn",
    listingLoadErr: "Erè chajman",
    listingCondition: "Kondisyon",
    listingContact: "Kontakte Vandè",
    listingOffer: "Fè yon Òf",
    listingOfferSent: "Òf voye!",
    listingChatErr: "Erè ouvri chat",
    inboxTitle: "Bwat Mesaj",
    noConversations: "Pa gen konvèsasyon",
    noConvHint: "Klik sou yon annons epi kontakte vandè a pou kòmanse.",
    sellTitle: "Kreye Annons",
    searchTitle: "Chèche",
    searchNoResults: "Pa gen rezilta",
    searchHint: "Eseye yon lòt mo rechèch.",
    chatOnline: "An liy",
    notVerifiedKyc: "Pa verifye",
  },
  fr: {
    tabHome: "Accueil",
    tabSearch: "Rechercher",
    tabSell: "Vendre",
    tabMessages: "Messages",
    tabProfile: "Profil",
    back: "Retour",
    loading: "Chargement...",
    cancel: "Annuler",
    save: "Enregistrer",
    ok: "OK",
    greeting: "Bonjour",
    allCategories: "Tout",
    noListings: "Aucune annonce",
    kycTitle: "Vérification d'identité",
    kycErrTitle: "Erreur",
    kycErrDocs: "Vous devez télécharger une photo de document et un selfie.",
    kycSubmitTitle: "Soumis !",
    kycSubmitMsg: "Votre demande KYC est soumise. L'admin la vérifiera dans 24 h.",
    kycErrMsg: "Échec de soumission. Réessayez.",
    kycDocType: "Type de document",
    kycNatId: "CIN",
    kycPassport: "Passeport",
    kycDrivingLicense: "Permis",
    kycDocFront: "Photo du document",
    kycDocFrontHint: "Prenez une photo recto du document",
    kycSelfie: "Selfie avec document",
    kycSelfieHint: "Selfie avec votre document en main",
    kycSubmitBtn: "Soumettre pour vérification",
    listingNotFound: "Annonce introuvable",
    listingLoadErr: "Erreur de chargement",
    back: "Retour",
    sponsored: "Sponsorisé",
    description: "Description",
    seller: "Vendeur",
    profile: "Profil",
    listingContact: "Message",
    listingOffer: "Faire une offre",
    myFavorites: "Mes Favoris",
    myOrders: "Mes Commandes",
    myWallet: "Portefeuille FM",
    myKyc: "Vérification (KYC)",
    myReviews: "Avis reçus",
    mySettings: "Paramètres",
    myListings: "Mes Annonces",
    seeAll: "Voir tout",
    logout: "Déconnexion",
    logoutTitle: "Déconnexion",
    logoutMsg: "Êtes-vous sûr de vouloir vous déconnecter ?",
    listingsCount: "Annonces",
    verified: "Vérifié",
    notVerified: "Non vérifié",
    rating: "Note",
    agentProfile: "Mon Profil Agent",
    sAccount: "Compte",
    sEditProfile: "Modifier le profil",
    sEditProfileHint: "Accédez au site FlexaMarket pour modifier votre profil.",
    sPasswordSecurity: "Mot de passe & Sécurité",
    sPasswordSecurityHint: "Allez dans Paramètres → Sécurité sur le site FlexaMarket pour changer votre mot de passe.",
    sKyc: "Vérification d'identité (KYC)",
    sPhone: "Téléphone & OTP",
    sPhoneHint: "Contactez le support FlexaMarket pour changer votre numéro de téléphone.",
    sPreferences: "Préférences",
    sNotifications: "Notifications",
    sNotifOn: "Activé",
    sNotifOff: "Désactivé",
    sLanguage: "Langue",
    sAppearance: "Apparence",
    sDarkMode: "Mode sombre",
    sFinances: "Finances",
    sWalletFM: "Portefeuille FM",
    sPayoutAccount: "Compte de paiement vendeur",
    sPayoutAccountHint: "Configurez votre compte MonCash et bancaire dans les Paramètres sur le site FlexaMarket.",
    sSupport: "Assistance",
    sHelpSupport: "Support",
    sHelpSupportHint: "Envoyez un message à support@flexamarket.com ou utilisez la section Support sur le site.",
    sTerms: "Conditions d'utilisation",
    sTermsHint: "Visitez flexamarket.com/terms pour lire les conditions d'utilisation.",
    sAbout: "À propos de FlexaMarket",
    sAboutMsg: "Premier marketplace d'achat & vente en Haïti.\n\nVersion 1.0.0\n© 2026 FlexaMarket",
    sLogout: "Déconnexion",
    ordersTitle: "Commandes",
    ordersBuying: "Achats",
    ordersSelling: "Ventes",
    noOrders: "Aucune commande",
    noOrdersHint: "Vos commandes apparaissent ici lorsque vous achetez ou vendez.",
    walletTitle: "Portefeuille FM",
    realBalance: "Solde Réel",
    promoBalance: "Promo",
    unlockedBalance: "Débloqué",
    recharge: "Recharger",
    send: "Envoyer",
    withdraw: "Retirer",
    noTransactions: "Aucune transaction",
    noTransactionsHint: "Vos transactions apparaissent ici.",
    txHistory: "Historique des transactions",
    rechargeTitle: "Recharger le portefeuille",
    rechargeMsg: "Envoyez MonCash au +509 40-40-1234 puis entrez le numéro de transaction dans le support.",
    sendTitle: "Envoyer de l'argent",
    sendMsg: "Utilisez la section 'Envoyer' sur le site FlexaMarket pour faire un transfert P2P.",
    withdrawTitle: "Retirer",
    withdrawMsg: "Contactez le support pour demander un retrait.",
    kycTitle: "Vérification d'identité",
    kycApproved: "Identité vérifiée ✅",
    kycApprovedSub: "Votre compte est vérifié. Vous pouvez effectuer toutes les transactions sans limite.",
    kycPending: "En attente de révision",
    kycPendingSub: "Votre demande a été soumise. L'administrateur la révisera dans les 24 heures.",
    kycRejected: "Demande refusée",
    kycInfoText: "La vérification d'identité est obligatoire pour les transferts de plus de 500 $ et les grandes transactions.",
    kycSubmitTitle: "Soumis !",
    kycSubmitMsg: "Votre demande KYC a été soumise. L'administrateur la révisera dans les 24 heures.",
    kycErrTitle: "Erreur",
    kycErrMsg: "Échec de la soumission. Réessayez.",
    kycErrDocs: "Vous devez télécharger la photo du document et le selfie.",
    kycSubmitting: "Envoi en cours...",
    kycDocType: "Type de document",
    kycNatId: "Carte nationale",
    kycPassport: "Passeport",
    kycDrivingLicense: "Permis de conduire",
    kycDocFront: "Photo de la pièce d'identité",
    kycDocFrontHint: "Cliquez pour télécharger le recto de votre pièce d'identité",
    kycSelfie: "Selfie",
    kycSelfieHint: "Cliquez pour télécharger un selfie",
    kycSubmitBtn: "Soumettre la vérification",
    listingNotFound: "Annonce introuvable",
    listingLoadErr: "Erreur de chargement",
    listingCondition: "État",
    listingContact: "Contacter le vendeur",
    listingOffer: "Faire une offre",
    listingOfferSent: "Offre envoyée !",
    listingChatErr: "Erreur d'ouverture du chat",
    inboxTitle: "Messages",
    noConversations: "Aucune conversation",
    noConvHint: "Cliquez sur une annonce et contactez le vendeur pour commencer.",
    sellTitle: "Créer une annonce",
    searchTitle: "Rechercher",
    searchNoResults: "Aucun résultat",
    searchHint: "Essayez un autre mot-clé.",
    chatOnline: "En ligne",
    notVerifiedKyc: "Non vérifié",
  },
};

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => Promise<void>;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "ht",
  setLang: async () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>("ht");

  useEffect(() => {
    AsyncStorage.getItem(LANG_KEY).then((v) => {
      if (v === "ht" || v === "fr") setLangState(v as Lang);
    });
  }, []);

  const setLang = useCallback(async (l: Lang) => {
    setLangState(l);
    await AsyncStorage.setItem(LANG_KEY, l);
  }, []);

  const t = useCallback(
    (key: string): string => T[lang][key] ?? T.ht[key] ?? key,
    [lang]
  );

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
