import { pgTable, serial, text, integer, jsonb, timestamp, boolean } from "drizzle-orm/pg-core";

export const adminAuditLogsTable = pgTable("admin_audit_logs", {
  id:               serial("id").primaryKey(),
  auditId:          text("audit_id").notNull().unique(),
  traceId:          text("trace_id").notNull().unique(),
  actorId:          integer("actor_id").notNull(),
  actorName:        text("actor_name"),
  actorRole:        text("actor_role"),
  actionType:       text("action_type").notNull(),
  actionCategory:   text("action_category").notNull(),
  targetType:       text("target_type"),
  targetId:         integer("target_id"),
  targetName:       text("target_name"),
  description:      text("description").notNull(),
  beforeState:      jsonb("before_state"),
  afterState:       jsonb("after_state"),
  metadata:         jsonb("metadata"),
  ipAddress:        text("ip_address"),
  userAgent:        text("user_agent"),
  deviceFingerprint:text("device_fingerprint"),
  geolocation:      text("geolocation"),
  sessionId:        text("session_id"),
  riskLevel:        text("risk_level").notNull().default("low"),
  status:           text("status").notNull().default("completed"),
  flagged:          boolean("flagged").notNull().default(false),
  flagReason:       text("flag_reason"),
  createdAt:        timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
