import { pgTable, text, serial, timestamp, integer, real, boolean, index } from "drizzle-orm/pg-core";
import { usersTable } from "./users";
import { transactionsTable } from "./transactions";
import { listingsTable } from "./listings";

export const driverApplicationsTable = pgTable("driver_applications", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull().references(() => usersTable.id),
  status: text("status").notNull().default("pending"),
  firstName: text("first_name").notNull(),
  lastName: text("last_name").notNull(),
  dateOfBirth: text("date_of_birth").notNull(),
  address: text("address").notNull(),
  city: text("city").notNull(),
  country: text("country").notNull(),
  whatsappNumber: text("whatsapp_number").notNull(),
  callPhone: text("call_phone").notNull(),
  hasSmartphone: boolean("has_smartphone").notNull().default(false),
  hasStableInternet: boolean("has_stable_internet").notNull().default(false),
  hasFastPhone: boolean("has_fast_phone").notNull().default(false),
  phoneBrand: text("phone_brand"),
  phoneModel: text("phone_model"),
  phoneOs: text("phone_os"),
  internetProvider: text("internet_provider"),
  vehicleType: text("vehicle_type"),
  vehicleBrand: text("vehicle_brand"),
  vehicleModel: text("vehicle_model"),
  vehicleYear: text("vehicle_year"),
  vehicleColor: text("vehicle_color"),
  licensePlateNumber: text("license_plate_number"),
  licenseNumber: text("license_number"),
  licenseExpiry: text("license_expiry"),
  photoFront: text("photo_front"),
  photoSide: text("photo_side"),
  photoBody: text("photo_body"),
  photoIdSelfie: text("photo_id_selfie"),
  // New dedicated document photo fields (added migration 202-208)
  photoVehicleRegistration: text("photo_vehicle_registration"),
  photoVehicleInsurance: text("photo_vehicle_insurance"),
  photoLicenseFront: text("photo_license_front"),
  photoLicenseBack: text("photo_license_back"),
  photoVehicleFront: text("photo_vehicle_front"),
  photoVehicleSide: text("photo_vehicle_side"),
  photoLicensePlate: text("photo_license_plate"),
  facePhotoFront: text("face_photo_front"),
  facePhotoLeft: text("face_photo_left"),
  facePhotoRight: text("face_photo_right"),
  facePhotoHoldingId: text("face_photo_holding_id"),
  // New vehicle photo (back angle)
  photoVehicleBack: text("photo_vehicle_back"),
  // Insurance / registration number on vehicle
  insuranceNumber: text("insurance_number"),
  // Selfie verification photo
  selfiePhotoUrl: text("selfie_photo_url"),
  // Banking / payout info
  bankName: text("bank_name"),
  bankAccountName: text("bank_account_name"),
  bankAccountNumber: text("bank_account_number"),
  preferredPaymentMethod: text("preferred_payment_method"),
  // Availability settings (stored as JSON strings)
  workZones: text("work_zones"),
  workHours: text("work_hours"),
  maxDeliveryKm: integer("max_delivery_km"),
  adminNote: text("admin_note"),
  allowEdit: boolean("allow_edit").notNull().default(false),
  reviewedById: integer("reviewed_by_id").references(() => usersTable.id),
  reviewedAt: timestamp("reviewed_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  byUserId: index("driver_applications_user_id_idx").on(t.userId),
  byStatus: index("driver_applications_status_idx").on(t.status),
}));

export const driversTable = pgTable("drivers", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull().references(() => usersTable.id),
  applicationId: integer("application_id").references(() => driverApplicationsTable.id),
  status: text("status").notNull().default("active"),
  country: text("country").notNull(),
  city: text("city"),
  vehicleType: text("vehicle_type"),
  vehicleBrand: text("vehicle_brand"),
  vehicleModel: text("vehicle_model"),
  vehicleYear: text("vehicle_year"),
  vehicleColor: text("vehicle_color"),
  licensePlateNumber: text("license_plate_number"),
  photoFront: text("photo_front"),
  photoSide: text("photo_side"),
  facePhotoFront: text("face_photo_front"),
  facePhotoLeft: text("face_photo_left"),
  facePhotoRight: text("face_photo_right"),
  facePhotoHoldingId: text("face_photo_holding_id"),
  rating: real("rating").notNull().default(0),
  reviewCount: integer("review_count").notNull().default(0),
  flaggedForReview: boolean("flagged_for_review").notNull().default(false),
  tipsTotal: real("tips_total").notNull().default(0),
  deliveryCount: integer("delivery_count").notNull().default(0),
  earningsTotal: real("earnings_total").notNull().default(0),
  latitude: real("latitude"),
  longitude: real("longitude"),
  commune: text("commune"),
  department: text("department"),
  zone: text("zone"),
  isOnline: boolean("is_online").notNull().default(false),
  lastLocationAt: timestamp("last_location_at", { withTimezone: true }),
  // Suspension details
  suspensionReason: text("suspension_reason"),
  suspendedUntil: timestamp("suspended_until", { withTimezone: true }),
  suspendedBy: integer("suspended_by").references(() => usersTable.id),
  suspendedAt: timestamp("suspended_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  byUserId: index("drivers_user_id_idx").on(t.userId),
  byCountry: index("drivers_country_idx").on(t.country),
}));

export const deliveriesTable = pgTable("deliveries", {
  id: serial("id").primaryKey(),
  transactionId: integer("transaction_id").references(() => transactionsTable.id),
  listingId: integer("listing_id").references(() => listingsTable.id),
  sellerId: integer("seller_id").notNull().references(() => usersTable.id),
  buyerId: integer("buyer_id").notNull().references(() => usersTable.id),
  driverId: integer("driver_id").references(() => driversTable.id),
  driverUserId: integer("driver_user_id").references(() => usersTable.id),
  deliveryMethod: text("delivery_method").notNull(),
  pickupAddress: text("pickup_address"),
  pickupCity: text("pickup_city"),
  deliveryAddress: text("delivery_address"),
  deliveryCity: text("delivery_city"),
  country: text("country").notNull(),
  status: text("status").notNull().default("waiting"),
  trackingNumber: text("tracking_number"),
  verificationCode: text("verification_code"),
  codeVerifiedAt: timestamp("code_verified_at", { withTimezone: true }),
  distanceMiles: real("distance_miles"),
  pricePerMile: real("price_per_mile"),
  totalAmount: real("total_amount"),
  driverEarnings: real("driver_earnings"),
  commissionAmount: real("commission_amount"),
  currency: text("currency").notNull().default("USD"),
  feeLocal: real("fee_local"),
  feeUsd: real("fee_usd"),
  distanceKm: real("distance_km"),
  tipUsd: real("tip_usd"),
  speedTier: text("speed_tier"),
  paymentHeldUntil: timestamp("payment_held_until", { withTimezone: true }),
  sellerPaymentReleased: boolean("seller_payment_released").notNull().default(false),
  sellerPaymentReleasedAt: timestamp("seller_payment_released_at", { withTimezone: true }),
  sellerNote: text("seller_note"),
  acceptedAt: timestamp("accepted_at", { withTimezone: true }),
  pickedUpAt: timestamp("picked_up_at", { withTimezone: true }),
  deliveredAt: timestamp("delivered_at", { withTimezone: true }),
  holdAmountUsd: real("hold_amount_usd"),
  holdReleased: boolean("hold_released").default(false),
  holdReleasedAt: timestamp("hold_released_at", { withTimezone: true }),
  returnCode: text("return_code"),
  returnConfirmedAt: timestamp("return_confirmed_at", { withTimezone: true }),
  failedPickupAt: timestamp("failed_pickup_at", { withTimezone: true }),
  returnFeeUsd: real("return_fee_usd"),
  arrivedAt: timestamp("arrived_at", { withTimezone: true }),
  buyerAbsentAt: timestamp("buyer_absent_at", { withTimezone: true }),
  buyerRescheduleDeadline: timestamp("buyer_reschedule_deadline", { withTimezone: true }),
  rescheduleCount: integer("reschedule_count").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  bySeller: index("deliveries_seller_id_idx").on(t.sellerId),
  byDriver: index("deliveries_driver_user_id_idx").on(t.driverUserId),
  byStatus: index("deliveries_status_idx").on(t.status),
  byTransaction: index("deliveries_transaction_id_idx").on(t.transactionId),
}));

export type DriverApplication = typeof driverApplicationsTable.$inferSelect;
export type Driver = typeof driversTable.$inferSelect;
export type Delivery = typeof deliveriesTable.$inferSelect;
